/* Verilog netlist generated by SCUBA Diamond (64-bit) 3.13.0.56.2 */
/* Module Version: 4.9 */
/* /home/user/FPGA/tools/diamond/usr/local/diamond/3.13/ispfpga/bin/lin64/scuba -w -n Multiplier -lang verilog -synth lse -bus_exp 7 -bb -arch sa5p00 -type dspmult -simple_portname -pfu_mult -widtha 12 -widthb 12 -widthp 24 -signed -PL_stages 1 -input_reg -output_reg -clk0 -ce0 -rst0 -fdc /home/user/Master Thesis/1bitSDR/1bitSDRLatticeTest/IP/Multiplier/Multiplier.fdc  */
/* Wed Feb 28 13:14:03 2024 */


`timescale 1 ns / 1 ps
module Multiplier (Clock, ClkEn, Aclr, DataA, DataB, Result)/* synthesis NGD_DRC_MASK=1 */;
    input wire Clock;
    input wire ClkEn;
    input wire Aclr;
    input wire [11:0] DataA;
    input wire [11:0] DataB;
    output wire [23:0] Result;

    wire rego_o_0;
    wire rego_o_1;
    wire rego_o_2;
    wire rego_o_3;
    wire rego_o_4;
    wire rego_o_5;
    wire rego_o_6;
    wire rego_o_7;
    wire f_Multiplier_0_pp_0_0;
    wire Multiplier_0_pp_0_0;
    wire f_Multiplier_0_pp_0_1;
    wire f_s_Multiplier_0_0_2;
    wire f_s_Multiplier_0_0_3;
    wire Multiplier_0_pp_2_4;
    wire Multiplier_0_pp_4_8;
    wire s_Multiplier_0_0_2;
    wire Multiplier_0_pp_1_2;
    wire s_Multiplier_0_0_3;
    wire s_Multiplier_0_0_4;
    wire co_Multiplier_0_0_1;
    wire s_Multiplier_0_0_5;
    wire s_Multiplier_0_0_6;
    wire co_Multiplier_0_0_2;
    wire s_Multiplier_0_0_7;
    wire s_Multiplier_0_0_8;
    wire co_Multiplier_0_0_3;
    wire s_Multiplier_0_0_9;
    wire s_Multiplier_0_0_10;
    wire co_Multiplier_0_0_4;
    wire s_Multiplier_0_0_11;
    wire s_Multiplier_0_0_12;
    wire co_Multiplier_0_0_5;
    wire s_Multiplier_0_0_13;
    wire s_Multiplier_0_0_14;
    wire Multiplier_0_pp_0_13;
    wire co_Multiplier_0_0_6;
    wire s_Multiplier_0_0_15;
    wire s_Multiplier_0_0_16;
    wire Multiplier_0_pp_1_15;
    wire co_Multiplier_0_0_7;
    wire s_Multiplier_0_0_17;
    wire co_Multiplier_0_0_8;
    wire s_Multiplier_0_1_6;
    wire Multiplier_0_pp_3_6;
    wire s_Multiplier_0_1_7;
    wire s_Multiplier_0_1_8;
    wire co_Multiplier_0_1_1;
    wire s_Multiplier_0_1_9;
    wire s_Multiplier_0_1_10;
    wire co_Multiplier_0_1_2;
    wire s_Multiplier_0_1_11;
    wire s_Multiplier_0_1_12;
    wire co_Multiplier_0_1_3;
    wire s_Multiplier_0_1_13;
    wire s_Multiplier_0_1_14;
    wire co_Multiplier_0_1_4;
    wire s_Multiplier_0_1_15;
    wire s_Multiplier_0_1_16;
    wire co_Multiplier_0_1_5;
    wire s_Multiplier_0_1_17;
    wire s_Multiplier_0_1_18;
    wire Multiplier_0_pp_2_17;
    wire co_Multiplier_0_1_6;
    wire s_Multiplier_0_1_19;
    wire s_Multiplier_0_1_20;
    wire Multiplier_0_pp_3_19;
    wire co_Multiplier_0_1_7;
    wire s_Multiplier_0_1_21;
    wire co_Multiplier_0_1_8;
    wire s_Multiplier_0_2_10;
    wire Multiplier_0_pp_5_10;
    wire s_Multiplier_0_2_11;
    wire s_Multiplier_0_2_12;
    wire co_Multiplier_0_2_1;
    wire s_Multiplier_0_2_13;
    wire s_Multiplier_0_2_14;
    wire co_Multiplier_0_2_2;
    wire s_Multiplier_0_2_15;
    wire s_Multiplier_0_2_16;
    wire co_Multiplier_0_2_3;
    wire s_Multiplier_0_2_17;
    wire s_Multiplier_0_2_18;
    wire co_Multiplier_0_2_4;
    wire s_Multiplier_0_2_19;
    wire s_Multiplier_0_2_20;
    wire co_Multiplier_0_2_5;
    wire s_Multiplier_0_2_21;
    wire s_Multiplier_0_2_22;
    wire Multiplier_0_pp_4_21;
    wire co_Multiplier_0_2_6;
    wire s_Multiplier_0_2_23;
    wire co_Multiplier_0_2_8;
    wire Multiplier_0_pp_5_23;
    wire co_Multiplier_0_2_7;
    wire s_Multiplier_0_3_4;
    wire f_Multiplier_0_pp_2_4;
    wire f_s_Multiplier_0_0_4;
    wire s_Multiplier_0_3_5;
    wire s_Multiplier_0_3_6;
    wire f_s_Multiplier_0_1_6;
    wire f_Multiplier_0_pp_2_5;
    wire f_s_Multiplier_0_0_6;
    wire f_s_Multiplier_0_0_5;
    wire co_Multiplier_0_3_1;
    wire s_Multiplier_0_3_7;
    wire f_s_Multiplier_0_1_8;
    wire f_s_Multiplier_0_1_7;
    wire f_s_Multiplier_0_0_8;
    wire f_s_Multiplier_0_0_7;
    wire co_Multiplier_0_3_2;
    wire f_s_Multiplier_0_1_10;
    wire f_s_Multiplier_0_1_9;
    wire f_s_Multiplier_0_0_10;
    wire f_s_Multiplier_0_0_9;
    wire co_Multiplier_0_3_3;
    wire f_s_Multiplier_0_1_12;
    wire f_s_Multiplier_0_1_11;
    wire f_s_Multiplier_0_0_12;
    wire f_s_Multiplier_0_0_11;
    wire co_Multiplier_0_3_4;
    wire f_s_Multiplier_0_1_14;
    wire f_s_Multiplier_0_1_13;
    wire f_s_Multiplier_0_0_14;
    wire f_s_Multiplier_0_0_13;
    wire co_Multiplier_0_3_5;
    wire f_s_Multiplier_0_1_16;
    wire f_s_Multiplier_0_1_15;
    wire f_s_Multiplier_0_0_16;
    wire f_s_Multiplier_0_0_15;
    wire co_Multiplier_0_3_6;
    wire f_s_Multiplier_0_1_18;
    wire f_s_Multiplier_0_1_17;
    wire f_s_Multiplier_0_0_17;
    wire co_Multiplier_0_3_7;
    wire f_s_Multiplier_0_1_20;
    wire f_s_Multiplier_0_1_19;
    wire co_Multiplier_0_3_8;
    wire f_s_Multiplier_0_1_21;
    wire co_Multiplier_0_3_9;
    wire co_Multiplier_0_3_10;
    wire rego_o_8;
    wire f_Multiplier_0_pp_4_8;
    wire s_Multiplier_0_3_8;
    wire rego_o_9;
    wire rego_o_10;
    wire f_s_Multiplier_0_2_10;
    wire f_Multiplier_0_pp_4_9;
    wire s_Multiplier_0_3_10;
    wire s_Multiplier_0_3_9;
    wire co_t_Multiplier_0_4_1;
    wire rego_o_11;
    wire rego_o_12;
    wire f_s_Multiplier_0_2_12;
    wire f_s_Multiplier_0_2_11;
    wire s_Multiplier_0_3_12;
    wire s_Multiplier_0_3_11;
    wire co_t_Multiplier_0_4_2;
    wire rego_o_13;
    wire rego_o_14;
    wire f_s_Multiplier_0_2_14;
    wire f_s_Multiplier_0_2_13;
    wire s_Multiplier_0_3_14;
    wire s_Multiplier_0_3_13;
    wire co_t_Multiplier_0_4_3;
    wire rego_o_15;
    wire rego_o_16;
    wire f_s_Multiplier_0_2_16;
    wire f_s_Multiplier_0_2_15;
    wire s_Multiplier_0_3_16;
    wire s_Multiplier_0_3_15;
    wire co_t_Multiplier_0_4_4;
    wire rego_o_17;
    wire rego_o_18;
    wire f_s_Multiplier_0_2_18;
    wire f_s_Multiplier_0_2_17;
    wire s_Multiplier_0_3_18;
    wire s_Multiplier_0_3_17;
    wire co_t_Multiplier_0_4_5;
    wire rego_o_19;
    wire rego_o_20;
    wire f_s_Multiplier_0_2_20;
    wire f_s_Multiplier_0_2_19;
    wire s_Multiplier_0_3_20;
    wire s_Multiplier_0_3_19;
    wire co_t_Multiplier_0_4_6;
    wire rego_o_21;
    wire rego_o_22;
    wire f_s_Multiplier_0_2_22;
    wire f_s_Multiplier_0_2_21;
    wire s_Multiplier_0_3_22;
    wire s_Multiplier_0_3_21;
    wire co_t_Multiplier_0_4_7;
    wire rego_o_23;
    wire co_t_Multiplier_0_4_9;
    wire f_s_Multiplier_0_2_23;
    wire s_Multiplier_0_3_23;
    wire co_t_Multiplier_0_4_8;
    wire Multiplier_0_pp_0_2;
    wire Multiplier_0_pp_0_1;
    wire Multiplier_0_cin_lr_0;
    wire Multiplier_0_pp_0_4;
    wire Multiplier_0_pp_0_3;
    wire mco;
    wire Multiplier_0_pp_0_6;
    wire Multiplier_0_pp_0_5;
    wire mco_1;
    wire Multiplier_0_pp_0_8;
    wire Multiplier_0_pp_0_7;
    wire mco_2;
    wire Multiplier_0_pp_0_10;
    wire Multiplier_0_pp_0_9;
    wire mco_3;
    wire regb_b_0;
    wire mfco;
    wire Multiplier_0_pp_0_12;
    wire Multiplier_0_pp_0_11;
    wire mco_4;
    wire regb_b_1;
    wire Multiplier_0_mult_0_5_n1;
    wire Multiplier_0_mult_0_5_n2;
    wire Multiplier_0_pp_1_4;
    wire Multiplier_0_pp_1_3;
    wire Multiplier_0_cin_lr_2;
    wire Multiplier_0_pp_1_6;
    wire Multiplier_0_pp_1_5;
    wire mco_5;
    wire Multiplier_0_pp_1_8;
    wire Multiplier_0_pp_1_7;
    wire mco_6;
    wire Multiplier_0_pp_1_10;
    wire Multiplier_0_pp_1_9;
    wire mco_7;
    wire Multiplier_0_pp_1_12;
    wire Multiplier_0_pp_1_11;
    wire mco_8;
    wire mfco_1;
    wire Multiplier_0_pp_1_14;
    wire Multiplier_0_pp_1_13;
    wire mco_9;
    wire regb_b_2;
    wire regb_b_3;
    wire Multiplier_0_mult_2_5_n1;
    wire Multiplier_0_mult_2_5_n2;
    wire Multiplier_0_pp_2_6;
    wire Multiplier_0_pp_2_5;
    wire Multiplier_0_cin_lr_4;
    wire Multiplier_0_pp_2_8;
    wire Multiplier_0_pp_2_7;
    wire mco_10;
    wire Multiplier_0_pp_2_10;
    wire Multiplier_0_pp_2_9;
    wire mco_11;
    wire Multiplier_0_pp_2_12;
    wire Multiplier_0_pp_2_11;
    wire mco_12;
    wire Multiplier_0_pp_2_14;
    wire Multiplier_0_pp_2_13;
    wire mco_13;
    wire mfco_2;
    wire Multiplier_0_pp_2_16;
    wire Multiplier_0_pp_2_15;
    wire mco_14;
    wire regb_b_4;
    wire regb_b_5;
    wire Multiplier_0_mult_4_5_n1;
    wire Multiplier_0_mult_4_5_n2;
    wire Multiplier_0_pp_3_8;
    wire Multiplier_0_pp_3_7;
    wire Multiplier_0_cin_lr_6;
    wire Multiplier_0_pp_3_10;
    wire Multiplier_0_pp_3_9;
    wire mco_15;
    wire Multiplier_0_pp_3_12;
    wire Multiplier_0_pp_3_11;
    wire mco_16;
    wire Multiplier_0_pp_3_14;
    wire Multiplier_0_pp_3_13;
    wire mco_17;
    wire Multiplier_0_pp_3_16;
    wire Multiplier_0_pp_3_15;
    wire mco_18;
    wire mfco_3;
    wire Multiplier_0_pp_3_18;
    wire Multiplier_0_pp_3_17;
    wire mco_19;
    wire regb_b_6;
    wire regb_b_7;
    wire Multiplier_0_mult_6_5_n1;
    wire Multiplier_0_mult_6_5_n2;
    wire Multiplier_0_pp_4_10;
    wire Multiplier_0_pp_4_9;
    wire Multiplier_0_cin_lr_8;
    wire rega_a_0;
    wire Multiplier_0_pp_4_12;
    wire Multiplier_0_pp_4_11;
    wire mco_20;
    wire Multiplier_0_pp_4_14;
    wire Multiplier_0_pp_4_13;
    wire mco_21;
    wire Multiplier_0_pp_4_16;
    wire Multiplier_0_pp_4_15;
    wire mco_22;
    wire Multiplier_0_pp_4_18;
    wire Multiplier_0_pp_4_17;
    wire mco_23;
    wire mfco_4;
    wire Multiplier_0_pp_4_20;
    wire Multiplier_0_pp_4_19;
    wire mco_24;
    wire regb_b_8;
    wire regb_b_9;
    wire Multiplier_0_mult_8_5_n1;
    wire Multiplier_0_mult_8_5_n2;
    wire Multiplier_0_pp_5_12;
    wire Multiplier_0_pp_5_11;
    wire Multiplier_0_cin_lr_10;
    wire rega_a_2;
    wire Multiplier_0_mult_10_0_n1;
    wire rega_a_1;
    wire Multiplier_0_mult_10_0_n0;
    wire Multiplier_0_pp_5_14;
    wire Multiplier_0_pp_5_13;
    wire mco_25;
    wire rega_a_4;
    wire Multiplier_0_mult_10_1_n1;
    wire rega_a_3;
    wire Multiplier_0_mult_10_1_n0;
    wire Multiplier_0_pp_5_16;
    wire Multiplier_0_pp_5_15;
    wire mco_26;
    wire rega_a_6;
    wire Multiplier_0_mult_10_2_n1;
    wire rega_a_5;
    wire Multiplier_0_mult_10_2_n0;
    wire Multiplier_0_pp_5_18;
    wire Multiplier_0_pp_5_17;
    wire mco_27;
    wire rega_a_8;
    wire Multiplier_0_mult_10_3_n1;
    wire rega_a_7;
    wire Multiplier_0_mult_10_3_n0;
    wire Multiplier_0_pp_5_20;
    wire Multiplier_0_pp_5_19;
    wire mco_28;
    wire rega_a_10;
    wire Multiplier_0_mult_10_4_n1;
    wire rega_a_9;
    wire Multiplier_0_mult_10_4_n0;
    wire mfco_5;
    wire Multiplier_0_pp_5_22;
    wire Multiplier_0_pp_5_21;
    wire mco_29;
    wire regb_b_10;
    wire regb_b_11;
    wire scuba_vhi;
    wire scuba_vlo;
    wire rega_a_11;
    wire Multiplier_0_mult_10_5_n2;
    wire Multiplier_0_mult_10_5_n0;

    AND2 AND2_t27 (.A(rega_a_0), .B(regb_b_0), .Z(Multiplier_0_pp_0_0));

    ND2 ND2_t26 (.A(rega_a_11), .B(regb_b_0), .Z(Multiplier_0_mult_0_5_n2));

    ND2 ND2_t25 (.A(rega_a_11), .B(regb_b_1), .Z(Multiplier_0_mult_0_5_n1));

    AND2 AND2_t24 (.A(rega_a_0), .B(regb_b_2), .Z(Multiplier_0_pp_1_2));

    ND2 ND2_t23 (.A(rega_a_11), .B(regb_b_2), .Z(Multiplier_0_mult_2_5_n2));

    ND2 ND2_t22 (.A(rega_a_11), .B(regb_b_3), .Z(Multiplier_0_mult_2_5_n1));

    AND2 AND2_t21 (.A(rega_a_0), .B(regb_b_4), .Z(Multiplier_0_pp_2_4));

    ND2 ND2_t20 (.A(rega_a_11), .B(regb_b_4), .Z(Multiplier_0_mult_4_5_n2));

    ND2 ND2_t19 (.A(rega_a_11), .B(regb_b_5), .Z(Multiplier_0_mult_4_5_n1));

    AND2 AND2_t18 (.A(rega_a_0), .B(regb_b_6), .Z(Multiplier_0_pp_3_6));

    ND2 ND2_t17 (.A(rega_a_11), .B(regb_b_6), .Z(Multiplier_0_mult_6_5_n2));

    ND2 ND2_t16 (.A(rega_a_11), .B(regb_b_7), .Z(Multiplier_0_mult_6_5_n1));

    AND2 AND2_t15 (.A(rega_a_0), .B(regb_b_8), .Z(Multiplier_0_pp_4_8));

    ND2 ND2_t14 (.A(rega_a_11), .B(regb_b_8), .Z(Multiplier_0_mult_8_5_n2));

    ND2 ND2_t13 (.A(rega_a_11), .B(regb_b_9), .Z(Multiplier_0_mult_8_5_n1));

    AND2 AND2_t12 (.A(rega_a_0), .B(regb_b_10), .Z(Multiplier_0_pp_5_10));

    ND2 ND2_t11 (.A(rega_a_1), .B(regb_b_11), .Z(Multiplier_0_mult_10_0_n1));

    ND2 ND2_t10 (.A(rega_a_0), .B(regb_b_11), .Z(Multiplier_0_mult_10_0_n0));

    ND2 ND2_t9 (.A(rega_a_3), .B(regb_b_11), .Z(Multiplier_0_mult_10_1_n1));

    ND2 ND2_t8 (.A(rega_a_2), .B(regb_b_11), .Z(Multiplier_0_mult_10_1_n0));

    ND2 ND2_t7 (.A(rega_a_5), .B(regb_b_11), .Z(Multiplier_0_mult_10_2_n1));

    ND2 ND2_t6 (.A(rega_a_4), .B(regb_b_11), .Z(Multiplier_0_mult_10_2_n0));

    ND2 ND2_t5 (.A(rega_a_7), .B(regb_b_11), .Z(Multiplier_0_mult_10_3_n1));

    ND2 ND2_t4 (.A(rega_a_6), .B(regb_b_11), .Z(Multiplier_0_mult_10_3_n0));

    ND2 ND2_t3 (.A(rega_a_9), .B(regb_b_11), .Z(Multiplier_0_mult_10_4_n1));

    ND2 ND2_t2 (.A(rega_a_8), .B(regb_b_11), .Z(Multiplier_0_mult_10_4_n0));

    ND2 ND2_t1 (.A(rega_a_11), .B(regb_b_10), .Z(Multiplier_0_mult_10_5_n2));

    ND2 ND2_t0 (.A(rega_a_10), .B(regb_b_11), .Z(Multiplier_0_mult_10_5_n0));

    FD1P3DX FF_99 (.D(DataA[0]), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(rega_a_0))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_98 (.D(DataA[1]), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(rega_a_1))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_97 (.D(DataA[2]), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(rega_a_2))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_96 (.D(DataA[3]), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(rega_a_3))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_95 (.D(DataA[4]), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(rega_a_4))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_94 (.D(DataA[5]), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(rega_a_5))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_93 (.D(DataA[6]), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(rega_a_6))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_92 (.D(DataA[7]), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(rega_a_7))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_91 (.D(DataA[8]), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(rega_a_8))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_90 (.D(DataA[9]), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(rega_a_9))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_89 (.D(DataA[10]), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(rega_a_10))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_88 (.D(DataA[11]), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(rega_a_11))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_87 (.D(DataB[0]), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(regb_b_0))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_86 (.D(DataB[1]), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(regb_b_1))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_85 (.D(DataB[2]), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(regb_b_2))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_84 (.D(DataB[3]), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(regb_b_3))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_83 (.D(DataB[4]), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(regb_b_4))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_82 (.D(DataB[5]), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(regb_b_5))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_81 (.D(DataB[6]), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(regb_b_6))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_80 (.D(DataB[7]), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(regb_b_7))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_79 (.D(DataB[8]), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(regb_b_8))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_78 (.D(DataB[9]), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(regb_b_9))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_77 (.D(DataB[10]), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(regb_b_10))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_76 (.D(DataB[11]), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(regb_b_11))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_75 (.D(rego_o_0), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(Result[0]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_74 (.D(rego_o_1), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(Result[1]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_73 (.D(rego_o_2), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(Result[2]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_72 (.D(rego_o_3), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(Result[3]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_71 (.D(rego_o_4), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(Result[4]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_70 (.D(rego_o_5), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(Result[5]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_69 (.D(rego_o_6), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(Result[6]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_68 (.D(rego_o_7), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(Result[7]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_67 (.D(rego_o_8), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(Result[8]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_66 (.D(rego_o_9), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(Result[9]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_65 (.D(rego_o_10), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(Result[10]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_64 (.D(rego_o_11), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(Result[11]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_63 (.D(rego_o_12), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(Result[12]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_62 (.D(rego_o_13), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(Result[13]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_61 (.D(rego_o_14), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(Result[14]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_60 (.D(rego_o_15), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(Result[15]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_59 (.D(rego_o_16), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(Result[16]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_58 (.D(rego_o_17), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(Result[17]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_57 (.D(rego_o_18), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(Result[18]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_56 (.D(rego_o_19), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(Result[19]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_55 (.D(rego_o_20), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(Result[20]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_54 (.D(rego_o_21), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(Result[21]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_53 (.D(rego_o_22), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(Result[22]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_52 (.D(rego_o_23), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(Result[23]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_51 (.D(Multiplier_0_pp_0_0), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_Multiplier_0_pp_0_0))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_50 (.D(Multiplier_0_pp_0_1), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_Multiplier_0_pp_0_1))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_49 (.D(s_Multiplier_0_0_2), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_Multiplier_0_0_2))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_48 (.D(s_Multiplier_0_0_3), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_Multiplier_0_0_3))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_47 (.D(s_Multiplier_0_0_4), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_Multiplier_0_0_4))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_46 (.D(s_Multiplier_0_0_5), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_Multiplier_0_0_5))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_45 (.D(s_Multiplier_0_0_6), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_Multiplier_0_0_6))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_44 (.D(s_Multiplier_0_0_7), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_Multiplier_0_0_7))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_43 (.D(s_Multiplier_0_0_8), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_Multiplier_0_0_8))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_42 (.D(s_Multiplier_0_0_9), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_Multiplier_0_0_9))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_41 (.D(s_Multiplier_0_0_10), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_Multiplier_0_0_10))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_40 (.D(s_Multiplier_0_0_11), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_Multiplier_0_0_11))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_39 (.D(s_Multiplier_0_0_12), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_Multiplier_0_0_12))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_38 (.D(s_Multiplier_0_0_13), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_Multiplier_0_0_13))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_37 (.D(s_Multiplier_0_0_14), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_Multiplier_0_0_14))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_36 (.D(s_Multiplier_0_0_15), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_Multiplier_0_0_15))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_35 (.D(s_Multiplier_0_0_16), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_Multiplier_0_0_16))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_34 (.D(s_Multiplier_0_0_17), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_Multiplier_0_0_17))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_33 (.D(Multiplier_0_pp_2_4), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_Multiplier_0_pp_2_4))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_32 (.D(Multiplier_0_pp_2_5), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_Multiplier_0_pp_2_5))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_31 (.D(s_Multiplier_0_1_6), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_Multiplier_0_1_6))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_30 (.D(s_Multiplier_0_1_7), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_Multiplier_0_1_7))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_29 (.D(s_Multiplier_0_1_8), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_Multiplier_0_1_8))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_28 (.D(s_Multiplier_0_1_9), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_Multiplier_0_1_9))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_27 (.D(s_Multiplier_0_1_10), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_Multiplier_0_1_10))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_26 (.D(s_Multiplier_0_1_11), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_Multiplier_0_1_11))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_25 (.D(s_Multiplier_0_1_12), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_Multiplier_0_1_12))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_24 (.D(s_Multiplier_0_1_13), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_Multiplier_0_1_13))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_23 (.D(s_Multiplier_0_1_14), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_Multiplier_0_1_14))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_22 (.D(s_Multiplier_0_1_15), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_Multiplier_0_1_15))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_21 (.D(s_Multiplier_0_1_16), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_Multiplier_0_1_16))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_20 (.D(s_Multiplier_0_1_17), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_Multiplier_0_1_17))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_19 (.D(s_Multiplier_0_1_18), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_Multiplier_0_1_18))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_18 (.D(s_Multiplier_0_1_19), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_Multiplier_0_1_19))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_17 (.D(s_Multiplier_0_1_20), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_Multiplier_0_1_20))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_16 (.D(s_Multiplier_0_1_21), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_Multiplier_0_1_21))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_15 (.D(Multiplier_0_pp_4_8), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_Multiplier_0_pp_4_8))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_14 (.D(Multiplier_0_pp_4_9), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_Multiplier_0_pp_4_9))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_13 (.D(s_Multiplier_0_2_10), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_Multiplier_0_2_10))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_12 (.D(s_Multiplier_0_2_11), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_Multiplier_0_2_11))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_11 (.D(s_Multiplier_0_2_12), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_Multiplier_0_2_12))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_10 (.D(s_Multiplier_0_2_13), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_Multiplier_0_2_13))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_9 (.D(s_Multiplier_0_2_14), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_Multiplier_0_2_14))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_8 (.D(s_Multiplier_0_2_15), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_Multiplier_0_2_15))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_7 (.D(s_Multiplier_0_2_16), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_Multiplier_0_2_16))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_6 (.D(s_Multiplier_0_2_17), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_Multiplier_0_2_17))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_5 (.D(s_Multiplier_0_2_18), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_Multiplier_0_2_18))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_4 (.D(s_Multiplier_0_2_19), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_Multiplier_0_2_19))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_3 (.D(s_Multiplier_0_2_20), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_Multiplier_0_2_20))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_2 (.D(s_Multiplier_0_2_21), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_Multiplier_0_2_21))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_1 (.D(s_Multiplier_0_2_22), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_Multiplier_0_2_22))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_0 (.D(s_Multiplier_0_2_23), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_Multiplier_0_2_23))
             /* synthesis GSR="ENABLED" */;

    defparam Multiplier_0_cin_lr_add_0.INJECT1_1 = "NO" ;
    defparam Multiplier_0_cin_lr_add_0.INJECT1_0 = "NO" ;
    defparam Multiplier_0_cin_lr_add_0.INIT1 =  16'h0000 ;
    defparam Multiplier_0_cin_lr_add_0.INIT0 =  16'h0000 ;
    CCU2C Multiplier_0_cin_lr_add_0 (.A0(scuba_vhi), .A1(scuba_vhi), .B0(scuba_vhi), 
        .B1(scuba_vhi), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(), .S0(), .S1(), .COUT(Multiplier_0_cin_lr_0));

    defparam Multiplier_0_Cadd_0_6.INJECT1_1 = "NO" ;
    defparam Multiplier_0_Cadd_0_6.INJECT1_0 = "NO" ;
    defparam Multiplier_0_Cadd_0_6.INIT1 =  16'h66AA ;
    defparam Multiplier_0_Cadd_0_6.INIT0 =  16'h66AA ;
    CCU2C Multiplier_0_Cadd_0_6 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo), 
        .B1(scuba_vlo), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(mfco), .S0(Multiplier_0_pp_0_13), .S1(), .COUT());

    defparam Multiplier_0_cin_lr_add_2.INJECT1_1 = "NO" ;
    defparam Multiplier_0_cin_lr_add_2.INJECT1_0 = "NO" ;
    defparam Multiplier_0_cin_lr_add_2.INIT1 =  16'h0000 ;
    defparam Multiplier_0_cin_lr_add_2.INIT0 =  16'h0000 ;
    CCU2C Multiplier_0_cin_lr_add_2 (.A0(scuba_vhi), .A1(scuba_vhi), .B0(scuba_vhi), 
        .B1(scuba_vhi), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(), .S0(), .S1(), .COUT(Multiplier_0_cin_lr_2));

    defparam Multiplier_0_Cadd_2_6.INJECT1_1 = "NO" ;
    defparam Multiplier_0_Cadd_2_6.INJECT1_0 = "NO" ;
    defparam Multiplier_0_Cadd_2_6.INIT1 =  16'h66AA ;
    defparam Multiplier_0_Cadd_2_6.INIT0 =  16'h66AA ;
    CCU2C Multiplier_0_Cadd_2_6 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo), 
        .B1(scuba_vlo), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(mfco_1), .S0(Multiplier_0_pp_1_15), .S1(), 
        .COUT());

    defparam Multiplier_0_cin_lr_add_4.INJECT1_1 = "NO" ;
    defparam Multiplier_0_cin_lr_add_4.INJECT1_0 = "NO" ;
    defparam Multiplier_0_cin_lr_add_4.INIT1 =  16'h0000 ;
    defparam Multiplier_0_cin_lr_add_4.INIT0 =  16'h0000 ;
    CCU2C Multiplier_0_cin_lr_add_4 (.A0(scuba_vhi), .A1(scuba_vhi), .B0(scuba_vhi), 
        .B1(scuba_vhi), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(), .S0(), .S1(), .COUT(Multiplier_0_cin_lr_4));

    defparam Multiplier_0_Cadd_4_6.INJECT1_1 = "NO" ;
    defparam Multiplier_0_Cadd_4_6.INJECT1_0 = "NO" ;
    defparam Multiplier_0_Cadd_4_6.INIT1 =  16'h66AA ;
    defparam Multiplier_0_Cadd_4_6.INIT0 =  16'h66AA ;
    CCU2C Multiplier_0_Cadd_4_6 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo), 
        .B1(scuba_vlo), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(mfco_2), .S0(Multiplier_0_pp_2_17), .S1(), 
        .COUT());

    defparam Multiplier_0_cin_lr_add_6.INJECT1_1 = "NO" ;
    defparam Multiplier_0_cin_lr_add_6.INJECT1_0 = "NO" ;
    defparam Multiplier_0_cin_lr_add_6.INIT1 =  16'h0000 ;
    defparam Multiplier_0_cin_lr_add_6.INIT0 =  16'h0000 ;
    CCU2C Multiplier_0_cin_lr_add_6 (.A0(scuba_vhi), .A1(scuba_vhi), .B0(scuba_vhi), 
        .B1(scuba_vhi), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(), .S0(), .S1(), .COUT(Multiplier_0_cin_lr_6));

    defparam Multiplier_0_Cadd_6_6.INJECT1_1 = "NO" ;
    defparam Multiplier_0_Cadd_6_6.INJECT1_0 = "NO" ;
    defparam Multiplier_0_Cadd_6_6.INIT1 =  16'h66AA ;
    defparam Multiplier_0_Cadd_6_6.INIT0 =  16'h66AA ;
    CCU2C Multiplier_0_Cadd_6_6 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo), 
        .B1(scuba_vlo), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(mfco_3), .S0(Multiplier_0_pp_3_19), .S1(), 
        .COUT());

    defparam Multiplier_0_cin_lr_add_8.INJECT1_1 = "NO" ;
    defparam Multiplier_0_cin_lr_add_8.INJECT1_0 = "NO" ;
    defparam Multiplier_0_cin_lr_add_8.INIT1 =  16'h0000 ;
    defparam Multiplier_0_cin_lr_add_8.INIT0 =  16'h0000 ;
    CCU2C Multiplier_0_cin_lr_add_8 (.A0(scuba_vhi), .A1(scuba_vhi), .B0(scuba_vhi), 
        .B1(scuba_vhi), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(), .S0(), .S1(), .COUT(Multiplier_0_cin_lr_8));

    defparam Multiplier_0_Cadd_8_6.INJECT1_1 = "NO" ;
    defparam Multiplier_0_Cadd_8_6.INJECT1_0 = "NO" ;
    defparam Multiplier_0_Cadd_8_6.INIT1 =  16'h66AA ;
    defparam Multiplier_0_Cadd_8_6.INIT0 =  16'h66AA ;
    CCU2C Multiplier_0_Cadd_8_6 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo), 
        .B1(scuba_vlo), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(mfco_4), .S0(Multiplier_0_pp_4_21), .S1(), 
        .COUT());

    defparam Multiplier_0_cin_lr_add_10.INJECT1_1 = "NO" ;
    defparam Multiplier_0_cin_lr_add_10.INJECT1_0 = "NO" ;
    defparam Multiplier_0_cin_lr_add_10.INIT1 =  16'h0000 ;
    defparam Multiplier_0_cin_lr_add_10.INIT0 =  16'h0000 ;
    CCU2C Multiplier_0_cin_lr_add_10 (.A0(scuba_vhi), .A1(scuba_vhi), .B0(scuba_vhi), 
        .B1(scuba_vhi), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(), .S0(), .S1(), .COUT(Multiplier_0_cin_lr_10));

    defparam Multiplier_0_Cadd_10_6.INJECT1_1 = "NO" ;
    defparam Multiplier_0_Cadd_10_6.INJECT1_0 = "NO" ;
    defparam Multiplier_0_Cadd_10_6.INIT1 =  16'h66AA ;
    defparam Multiplier_0_Cadd_10_6.INIT0 =  16'h66AA ;
    CCU2C Multiplier_0_Cadd_10_6 (.A0(scuba_vhi), .A1(scuba_vlo), .B0(scuba_vlo), 
        .B1(scuba_vlo), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(mfco_5), .S0(Multiplier_0_pp_5_23), .S1(), 
        .COUT());

    defparam Cadd_Multiplier_0_0_1.INJECT1_1 = "NO" ;
    defparam Cadd_Multiplier_0_0_1.INJECT1_0 = "NO" ;
    defparam Cadd_Multiplier_0_0_1.INIT1 =  16'h66AA ;
    defparam Cadd_Multiplier_0_0_1.INIT0 =  16'h66AA ;
    CCU2C Cadd_Multiplier_0_0_1 (.A0(scuba_vlo), .A1(Multiplier_0_pp_0_2), 
        .B0(scuba_vlo), .B1(Multiplier_0_pp_1_2), .C0(scuba_vhi), .C1(scuba_vhi), 
        .D0(scuba_vhi), .D1(scuba_vhi), .CIN(), .S0(), .S1(s_Multiplier_0_0_2), 
        .COUT(co_Multiplier_0_0_1));

    defparam Multiplier_0_add_0_2.INJECT1_1 = "NO" ;
    defparam Multiplier_0_add_0_2.INJECT1_0 = "NO" ;
    defparam Multiplier_0_add_0_2.INIT1 =  16'h66AA ;
    defparam Multiplier_0_add_0_2.INIT0 =  16'h66AA ;
    CCU2C Multiplier_0_add_0_2 (.A0(Multiplier_0_pp_0_3), .A1(Multiplier_0_pp_0_4), 
        .B0(Multiplier_0_pp_1_3), .B1(Multiplier_0_pp_1_4), .C0(scuba_vhi), 
        .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), .CIN(co_Multiplier_0_0_1), 
        .S0(s_Multiplier_0_0_3), .S1(s_Multiplier_0_0_4), .COUT(co_Multiplier_0_0_2));

    defparam Multiplier_0_add_0_3.INJECT1_1 = "NO" ;
    defparam Multiplier_0_add_0_3.INJECT1_0 = "NO" ;
    defparam Multiplier_0_add_0_3.INIT1 =  16'h66AA ;
    defparam Multiplier_0_add_0_3.INIT0 =  16'h66AA ;
    CCU2C Multiplier_0_add_0_3 (.A0(Multiplier_0_pp_0_5), .A1(Multiplier_0_pp_0_6), 
        .B0(Multiplier_0_pp_1_5), .B1(Multiplier_0_pp_1_6), .C0(scuba_vhi), 
        .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), .CIN(co_Multiplier_0_0_2), 
        .S0(s_Multiplier_0_0_5), .S1(s_Multiplier_0_0_6), .COUT(co_Multiplier_0_0_3));

    defparam Multiplier_0_add_0_4.INJECT1_1 = "NO" ;
    defparam Multiplier_0_add_0_4.INJECT1_0 = "NO" ;
    defparam Multiplier_0_add_0_4.INIT1 =  16'h66AA ;
    defparam Multiplier_0_add_0_4.INIT0 =  16'h66AA ;
    CCU2C Multiplier_0_add_0_4 (.A0(Multiplier_0_pp_0_7), .A1(Multiplier_0_pp_0_8), 
        .B0(Multiplier_0_pp_1_7), .B1(Multiplier_0_pp_1_8), .C0(scuba_vhi), 
        .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), .CIN(co_Multiplier_0_0_3), 
        .S0(s_Multiplier_0_0_7), .S1(s_Multiplier_0_0_8), .COUT(co_Multiplier_0_0_4));

    defparam Multiplier_0_add_0_5.INJECT1_1 = "NO" ;
    defparam Multiplier_0_add_0_5.INJECT1_0 = "NO" ;
    defparam Multiplier_0_add_0_5.INIT1 =  16'h66AA ;
    defparam Multiplier_0_add_0_5.INIT0 =  16'h66AA ;
    CCU2C Multiplier_0_add_0_5 (.A0(Multiplier_0_pp_0_9), .A1(Multiplier_0_pp_0_10), 
        .B0(Multiplier_0_pp_1_9), .B1(Multiplier_0_pp_1_10), .C0(scuba_vhi), 
        .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), .CIN(co_Multiplier_0_0_4), 
        .S0(s_Multiplier_0_0_9), .S1(s_Multiplier_0_0_10), .COUT(co_Multiplier_0_0_5));

    defparam Multiplier_0_add_0_6.INJECT1_1 = "NO" ;
    defparam Multiplier_0_add_0_6.INJECT1_0 = "NO" ;
    defparam Multiplier_0_add_0_6.INIT1 =  16'h66AA ;
    defparam Multiplier_0_add_0_6.INIT0 =  16'h66AA ;
    CCU2C Multiplier_0_add_0_6 (.A0(Multiplier_0_pp_0_11), .A1(Multiplier_0_pp_0_12), 
        .B0(Multiplier_0_pp_1_11), .B1(Multiplier_0_pp_1_12), .C0(scuba_vhi), 
        .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), .CIN(co_Multiplier_0_0_5), 
        .S0(s_Multiplier_0_0_11), .S1(s_Multiplier_0_0_12), .COUT(co_Multiplier_0_0_6));

    defparam Multiplier_0_add_0_7.INJECT1_1 = "NO" ;
    defparam Multiplier_0_add_0_7.INJECT1_0 = "NO" ;
    defparam Multiplier_0_add_0_7.INIT1 =  16'h66AA ;
    defparam Multiplier_0_add_0_7.INIT0 =  16'h66AA ;
    CCU2C Multiplier_0_add_0_7 (.A0(Multiplier_0_pp_0_13), .A1(scuba_vlo), 
        .B0(Multiplier_0_pp_1_13), .B1(Multiplier_0_pp_1_14), .C0(scuba_vhi), 
        .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), .CIN(co_Multiplier_0_0_6), 
        .S0(s_Multiplier_0_0_13), .S1(s_Multiplier_0_0_14), .COUT(co_Multiplier_0_0_7));

    defparam Multiplier_0_add_0_8.INJECT1_1 = "NO" ;
    defparam Multiplier_0_add_0_8.INJECT1_0 = "NO" ;
    defparam Multiplier_0_add_0_8.INIT1 =  16'h66AA ;
    defparam Multiplier_0_add_0_8.INIT0 =  16'h66AA ;
    CCU2C Multiplier_0_add_0_8 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(Multiplier_0_pp_1_15), 
        .B1(scuba_vlo), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co_Multiplier_0_0_7), .S0(s_Multiplier_0_0_15), 
        .S1(s_Multiplier_0_0_16), .COUT(co_Multiplier_0_0_8));

    defparam Cadd_Multiplier_0_0_9.INJECT1_1 = "NO" ;
    defparam Cadd_Multiplier_0_0_9.INJECT1_0 = "NO" ;
    defparam Cadd_Multiplier_0_0_9.INIT1 =  16'h66AA ;
    defparam Cadd_Multiplier_0_0_9.INIT0 =  16'h66AA ;
    CCU2C Cadd_Multiplier_0_0_9 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo), 
        .B1(scuba_vlo), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co_Multiplier_0_0_8), .S0(s_Multiplier_0_0_17), 
        .S1(), .COUT());

    defparam Cadd_Multiplier_0_1_1.INJECT1_1 = "NO" ;
    defparam Cadd_Multiplier_0_1_1.INJECT1_0 = "NO" ;
    defparam Cadd_Multiplier_0_1_1.INIT1 =  16'h66AA ;
    defparam Cadd_Multiplier_0_1_1.INIT0 =  16'h66AA ;
    CCU2C Cadd_Multiplier_0_1_1 (.A0(scuba_vlo), .A1(Multiplier_0_pp_2_6), 
        .B0(scuba_vlo), .B1(Multiplier_0_pp_3_6), .C0(scuba_vhi), .C1(scuba_vhi), 
        .D0(scuba_vhi), .D1(scuba_vhi), .CIN(), .S0(), .S1(s_Multiplier_0_1_6), 
        .COUT(co_Multiplier_0_1_1));

    defparam Multiplier_0_add_1_2.INJECT1_1 = "NO" ;
    defparam Multiplier_0_add_1_2.INJECT1_0 = "NO" ;
    defparam Multiplier_0_add_1_2.INIT1 =  16'h66AA ;
    defparam Multiplier_0_add_1_2.INIT0 =  16'h66AA ;
    CCU2C Multiplier_0_add_1_2 (.A0(Multiplier_0_pp_2_7), .A1(Multiplier_0_pp_2_8), 
        .B0(Multiplier_0_pp_3_7), .B1(Multiplier_0_pp_3_8), .C0(scuba_vhi), 
        .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), .CIN(co_Multiplier_0_1_1), 
        .S0(s_Multiplier_0_1_7), .S1(s_Multiplier_0_1_8), .COUT(co_Multiplier_0_1_2));

    defparam Multiplier_0_add_1_3.INJECT1_1 = "NO" ;
    defparam Multiplier_0_add_1_3.INJECT1_0 = "NO" ;
    defparam Multiplier_0_add_1_3.INIT1 =  16'h66AA ;
    defparam Multiplier_0_add_1_3.INIT0 =  16'h66AA ;
    CCU2C Multiplier_0_add_1_3 (.A0(Multiplier_0_pp_2_9), .A1(Multiplier_0_pp_2_10), 
        .B0(Multiplier_0_pp_3_9), .B1(Multiplier_0_pp_3_10), .C0(scuba_vhi), 
        .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), .CIN(co_Multiplier_0_1_2), 
        .S0(s_Multiplier_0_1_9), .S1(s_Multiplier_0_1_10), .COUT(co_Multiplier_0_1_3));

    defparam Multiplier_0_add_1_4.INJECT1_1 = "NO" ;
    defparam Multiplier_0_add_1_4.INJECT1_0 = "NO" ;
    defparam Multiplier_0_add_1_4.INIT1 =  16'h66AA ;
    defparam Multiplier_0_add_1_4.INIT0 =  16'h66AA ;
    CCU2C Multiplier_0_add_1_4 (.A0(Multiplier_0_pp_2_11), .A1(Multiplier_0_pp_2_12), 
        .B0(Multiplier_0_pp_3_11), .B1(Multiplier_0_pp_3_12), .C0(scuba_vhi), 
        .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), .CIN(co_Multiplier_0_1_3), 
        .S0(s_Multiplier_0_1_11), .S1(s_Multiplier_0_1_12), .COUT(co_Multiplier_0_1_4));

    defparam Multiplier_0_add_1_5.INJECT1_1 = "NO" ;
    defparam Multiplier_0_add_1_5.INJECT1_0 = "NO" ;
    defparam Multiplier_0_add_1_5.INIT1 =  16'h66AA ;
    defparam Multiplier_0_add_1_5.INIT0 =  16'h66AA ;
    CCU2C Multiplier_0_add_1_5 (.A0(Multiplier_0_pp_2_13), .A1(Multiplier_0_pp_2_14), 
        .B0(Multiplier_0_pp_3_13), .B1(Multiplier_0_pp_3_14), .C0(scuba_vhi), 
        .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), .CIN(co_Multiplier_0_1_4), 
        .S0(s_Multiplier_0_1_13), .S1(s_Multiplier_0_1_14), .COUT(co_Multiplier_0_1_5));

    defparam Multiplier_0_add_1_6.INJECT1_1 = "NO" ;
    defparam Multiplier_0_add_1_6.INJECT1_0 = "NO" ;
    defparam Multiplier_0_add_1_6.INIT1 =  16'h66AA ;
    defparam Multiplier_0_add_1_6.INIT0 =  16'h66AA ;
    CCU2C Multiplier_0_add_1_6 (.A0(Multiplier_0_pp_2_15), .A1(Multiplier_0_pp_2_16), 
        .B0(Multiplier_0_pp_3_15), .B1(Multiplier_0_pp_3_16), .C0(scuba_vhi), 
        .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), .CIN(co_Multiplier_0_1_5), 
        .S0(s_Multiplier_0_1_15), .S1(s_Multiplier_0_1_16), .COUT(co_Multiplier_0_1_6));

    defparam Multiplier_0_add_1_7.INJECT1_1 = "NO" ;
    defparam Multiplier_0_add_1_7.INJECT1_0 = "NO" ;
    defparam Multiplier_0_add_1_7.INIT1 =  16'h66AA ;
    defparam Multiplier_0_add_1_7.INIT0 =  16'h66AA ;
    CCU2C Multiplier_0_add_1_7 (.A0(Multiplier_0_pp_2_17), .A1(scuba_vlo), 
        .B0(Multiplier_0_pp_3_17), .B1(Multiplier_0_pp_3_18), .C0(scuba_vhi), 
        .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), .CIN(co_Multiplier_0_1_6), 
        .S0(s_Multiplier_0_1_17), .S1(s_Multiplier_0_1_18), .COUT(co_Multiplier_0_1_7));

    defparam Multiplier_0_add_1_8.INJECT1_1 = "NO" ;
    defparam Multiplier_0_add_1_8.INJECT1_0 = "NO" ;
    defparam Multiplier_0_add_1_8.INIT1 =  16'h66AA ;
    defparam Multiplier_0_add_1_8.INIT0 =  16'h66AA ;
    CCU2C Multiplier_0_add_1_8 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(Multiplier_0_pp_3_19), 
        .B1(scuba_vlo), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co_Multiplier_0_1_7), .S0(s_Multiplier_0_1_19), 
        .S1(s_Multiplier_0_1_20), .COUT(co_Multiplier_0_1_8));

    defparam Cadd_Multiplier_0_1_9.INJECT1_1 = "NO" ;
    defparam Cadd_Multiplier_0_1_9.INJECT1_0 = "NO" ;
    defparam Cadd_Multiplier_0_1_9.INIT1 =  16'h66AA ;
    defparam Cadd_Multiplier_0_1_9.INIT0 =  16'h66AA ;
    CCU2C Cadd_Multiplier_0_1_9 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo), 
        .B1(scuba_vlo), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co_Multiplier_0_1_8), .S0(s_Multiplier_0_1_21), 
        .S1(), .COUT());

    defparam Cadd_Multiplier_0_2_1.INJECT1_1 = "NO" ;
    defparam Cadd_Multiplier_0_2_1.INJECT1_0 = "NO" ;
    defparam Cadd_Multiplier_0_2_1.INIT1 =  16'h66AA ;
    defparam Cadd_Multiplier_0_2_1.INIT0 =  16'h66AA ;
    CCU2C Cadd_Multiplier_0_2_1 (.A0(scuba_vlo), .A1(Multiplier_0_pp_4_10), 
        .B0(scuba_vlo), .B1(Multiplier_0_pp_5_10), .C0(scuba_vhi), .C1(scuba_vhi), 
        .D0(scuba_vhi), .D1(scuba_vhi), .CIN(), .S0(), .S1(s_Multiplier_0_2_10), 
        .COUT(co_Multiplier_0_2_1));

    defparam Multiplier_0_add_2_2.INJECT1_1 = "NO" ;
    defparam Multiplier_0_add_2_2.INJECT1_0 = "NO" ;
    defparam Multiplier_0_add_2_2.INIT1 =  16'h66AA ;
    defparam Multiplier_0_add_2_2.INIT0 =  16'h66AA ;
    CCU2C Multiplier_0_add_2_2 (.A0(Multiplier_0_pp_4_11), .A1(Multiplier_0_pp_4_12), 
        .B0(Multiplier_0_pp_5_11), .B1(Multiplier_0_pp_5_12), .C0(scuba_vhi), 
        .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), .CIN(co_Multiplier_0_2_1), 
        .S0(s_Multiplier_0_2_11), .S1(s_Multiplier_0_2_12), .COUT(co_Multiplier_0_2_2));

    defparam Multiplier_0_add_2_3.INJECT1_1 = "NO" ;
    defparam Multiplier_0_add_2_3.INJECT1_0 = "NO" ;
    defparam Multiplier_0_add_2_3.INIT1 =  16'h66AA ;
    defparam Multiplier_0_add_2_3.INIT0 =  16'h66AA ;
    CCU2C Multiplier_0_add_2_3 (.A0(Multiplier_0_pp_4_13), .A1(Multiplier_0_pp_4_14), 
        .B0(Multiplier_0_pp_5_13), .B1(Multiplier_0_pp_5_14), .C0(scuba_vhi), 
        .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), .CIN(co_Multiplier_0_2_2), 
        .S0(s_Multiplier_0_2_13), .S1(s_Multiplier_0_2_14), .COUT(co_Multiplier_0_2_3));

    defparam Multiplier_0_add_2_4.INJECT1_1 = "NO" ;
    defparam Multiplier_0_add_2_4.INJECT1_0 = "NO" ;
    defparam Multiplier_0_add_2_4.INIT1 =  16'h66AA ;
    defparam Multiplier_0_add_2_4.INIT0 =  16'h66AA ;
    CCU2C Multiplier_0_add_2_4 (.A0(Multiplier_0_pp_4_15), .A1(Multiplier_0_pp_4_16), 
        .B0(Multiplier_0_pp_5_15), .B1(Multiplier_0_pp_5_16), .C0(scuba_vhi), 
        .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), .CIN(co_Multiplier_0_2_3), 
        .S0(s_Multiplier_0_2_15), .S1(s_Multiplier_0_2_16), .COUT(co_Multiplier_0_2_4));

    defparam Multiplier_0_add_2_5.INJECT1_1 = "NO" ;
    defparam Multiplier_0_add_2_5.INJECT1_0 = "NO" ;
    defparam Multiplier_0_add_2_5.INIT1 =  16'h66AA ;
    defparam Multiplier_0_add_2_5.INIT0 =  16'h66AA ;
    CCU2C Multiplier_0_add_2_5 (.A0(Multiplier_0_pp_4_17), .A1(Multiplier_0_pp_4_18), 
        .B0(Multiplier_0_pp_5_17), .B1(Multiplier_0_pp_5_18), .C0(scuba_vhi), 
        .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), .CIN(co_Multiplier_0_2_4), 
        .S0(s_Multiplier_0_2_17), .S1(s_Multiplier_0_2_18), .COUT(co_Multiplier_0_2_5));

    defparam Multiplier_0_add_2_6.INJECT1_1 = "NO" ;
    defparam Multiplier_0_add_2_6.INJECT1_0 = "NO" ;
    defparam Multiplier_0_add_2_6.INIT1 =  16'h66AA ;
    defparam Multiplier_0_add_2_6.INIT0 =  16'h66AA ;
    CCU2C Multiplier_0_add_2_6 (.A0(Multiplier_0_pp_4_19), .A1(Multiplier_0_pp_4_20), 
        .B0(Multiplier_0_pp_5_19), .B1(Multiplier_0_pp_5_20), .C0(scuba_vhi), 
        .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), .CIN(co_Multiplier_0_2_5), 
        .S0(s_Multiplier_0_2_19), .S1(s_Multiplier_0_2_20), .COUT(co_Multiplier_0_2_6));

    defparam Multiplier_0_add_2_7.INJECT1_1 = "NO" ;
    defparam Multiplier_0_add_2_7.INJECT1_0 = "NO" ;
    defparam Multiplier_0_add_2_7.INIT1 =  16'h66AA ;
    defparam Multiplier_0_add_2_7.INIT0 =  16'h66AA ;
    CCU2C Multiplier_0_add_2_7 (.A0(Multiplier_0_pp_4_21), .A1(scuba_vlo), 
        .B0(Multiplier_0_pp_5_21), .B1(Multiplier_0_pp_5_22), .C0(scuba_vhi), 
        .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), .CIN(co_Multiplier_0_2_6), 
        .S0(s_Multiplier_0_2_21), .S1(s_Multiplier_0_2_22), .COUT(co_Multiplier_0_2_7));

    defparam Multiplier_0_add_2_8.INJECT1_1 = "NO" ;
    defparam Multiplier_0_add_2_8.INJECT1_0 = "NO" ;
    defparam Multiplier_0_add_2_8.INIT1 =  16'h66AA ;
    defparam Multiplier_0_add_2_8.INIT0 =  16'h66AA ;
    CCU2C Multiplier_0_add_2_8 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(Multiplier_0_pp_5_23), 
        .B1(scuba_vlo), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co_Multiplier_0_2_7), .S0(s_Multiplier_0_2_23), 
        .S1(), .COUT(co_Multiplier_0_2_8));

    defparam Cadd_Multiplier_0_3_1.INJECT1_1 = "NO" ;
    defparam Cadd_Multiplier_0_3_1.INJECT1_0 = "NO" ;
    defparam Cadd_Multiplier_0_3_1.INIT1 =  16'h66AA ;
    defparam Cadd_Multiplier_0_3_1.INIT0 =  16'h66AA ;
    CCU2C Cadd_Multiplier_0_3_1 (.A0(scuba_vlo), .A1(f_s_Multiplier_0_0_4), 
        .B0(scuba_vlo), .B1(f_Multiplier_0_pp_2_4), .C0(scuba_vhi), .C1(scuba_vhi), 
        .D0(scuba_vhi), .D1(scuba_vhi), .CIN(), .S0(), .S1(s_Multiplier_0_3_4), 
        .COUT(co_Multiplier_0_3_1));

    defparam Multiplier_0_add_3_2.INJECT1_1 = "NO" ;
    defparam Multiplier_0_add_3_2.INJECT1_0 = "NO" ;
    defparam Multiplier_0_add_3_2.INIT1 =  16'h66AA ;
    defparam Multiplier_0_add_3_2.INIT0 =  16'h66AA ;
    CCU2C Multiplier_0_add_3_2 (.A0(f_s_Multiplier_0_0_5), .A1(f_s_Multiplier_0_0_6), 
        .B0(f_Multiplier_0_pp_2_5), .B1(f_s_Multiplier_0_1_6), .C0(scuba_vhi), 
        .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), .CIN(co_Multiplier_0_3_1), 
        .S0(s_Multiplier_0_3_5), .S1(s_Multiplier_0_3_6), .COUT(co_Multiplier_0_3_2));

    defparam Multiplier_0_add_3_3.INJECT1_1 = "NO" ;
    defparam Multiplier_0_add_3_3.INJECT1_0 = "NO" ;
    defparam Multiplier_0_add_3_3.INIT1 =  16'h66AA ;
    defparam Multiplier_0_add_3_3.INIT0 =  16'h66AA ;
    CCU2C Multiplier_0_add_3_3 (.A0(f_s_Multiplier_0_0_7), .A1(f_s_Multiplier_0_0_8), 
        .B0(f_s_Multiplier_0_1_7), .B1(f_s_Multiplier_0_1_8), .C0(scuba_vhi), 
        .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), .CIN(co_Multiplier_0_3_2), 
        .S0(s_Multiplier_0_3_7), .S1(s_Multiplier_0_3_8), .COUT(co_Multiplier_0_3_3));

    defparam Multiplier_0_add_3_4.INJECT1_1 = "NO" ;
    defparam Multiplier_0_add_3_4.INJECT1_0 = "NO" ;
    defparam Multiplier_0_add_3_4.INIT1 =  16'h66AA ;
    defparam Multiplier_0_add_3_4.INIT0 =  16'h66AA ;
    CCU2C Multiplier_0_add_3_4 (.A0(f_s_Multiplier_0_0_9), .A1(f_s_Multiplier_0_0_10), 
        .B0(f_s_Multiplier_0_1_9), .B1(f_s_Multiplier_0_1_10), .C0(scuba_vhi), 
        .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), .CIN(co_Multiplier_0_3_3), 
        .S0(s_Multiplier_0_3_9), .S1(s_Multiplier_0_3_10), .COUT(co_Multiplier_0_3_4));

    defparam Multiplier_0_add_3_5.INJECT1_1 = "NO" ;
    defparam Multiplier_0_add_3_5.INJECT1_0 = "NO" ;
    defparam Multiplier_0_add_3_5.INIT1 =  16'h66AA ;
    defparam Multiplier_0_add_3_5.INIT0 =  16'h66AA ;
    CCU2C Multiplier_0_add_3_5 (.A0(f_s_Multiplier_0_0_11), .A1(f_s_Multiplier_0_0_12), 
        .B0(f_s_Multiplier_0_1_11), .B1(f_s_Multiplier_0_1_12), .C0(scuba_vhi), 
        .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), .CIN(co_Multiplier_0_3_4), 
        .S0(s_Multiplier_0_3_11), .S1(s_Multiplier_0_3_12), .COUT(co_Multiplier_0_3_5));

    defparam Multiplier_0_add_3_6.INJECT1_1 = "NO" ;
    defparam Multiplier_0_add_3_6.INJECT1_0 = "NO" ;
    defparam Multiplier_0_add_3_6.INIT1 =  16'h66AA ;
    defparam Multiplier_0_add_3_6.INIT0 =  16'h66AA ;
    CCU2C Multiplier_0_add_3_6 (.A0(f_s_Multiplier_0_0_13), .A1(f_s_Multiplier_0_0_14), 
        .B0(f_s_Multiplier_0_1_13), .B1(f_s_Multiplier_0_1_14), .C0(scuba_vhi), 
        .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), .CIN(co_Multiplier_0_3_5), 
        .S0(s_Multiplier_0_3_13), .S1(s_Multiplier_0_3_14), .COUT(co_Multiplier_0_3_6));

    defparam Multiplier_0_add_3_7.INJECT1_1 = "NO" ;
    defparam Multiplier_0_add_3_7.INJECT1_0 = "NO" ;
    defparam Multiplier_0_add_3_7.INIT1 =  16'h66AA ;
    defparam Multiplier_0_add_3_7.INIT0 =  16'h66AA ;
    CCU2C Multiplier_0_add_3_7 (.A0(f_s_Multiplier_0_0_15), .A1(f_s_Multiplier_0_0_16), 
        .B0(f_s_Multiplier_0_1_15), .B1(f_s_Multiplier_0_1_16), .C0(scuba_vhi), 
        .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), .CIN(co_Multiplier_0_3_6), 
        .S0(s_Multiplier_0_3_15), .S1(s_Multiplier_0_3_16), .COUT(co_Multiplier_0_3_7));

    defparam Multiplier_0_add_3_8.INJECT1_1 = "NO" ;
    defparam Multiplier_0_add_3_8.INJECT1_0 = "NO" ;
    defparam Multiplier_0_add_3_8.INIT1 =  16'h66AA ;
    defparam Multiplier_0_add_3_8.INIT0 =  16'h66AA ;
    CCU2C Multiplier_0_add_3_8 (.A0(f_s_Multiplier_0_0_17), .A1(scuba_vlo), 
        .B0(f_s_Multiplier_0_1_17), .B1(f_s_Multiplier_0_1_18), .C0(scuba_vhi), 
        .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), .CIN(co_Multiplier_0_3_7), 
        .S0(s_Multiplier_0_3_17), .S1(s_Multiplier_0_3_18), .COUT(co_Multiplier_0_3_8));

    defparam Multiplier_0_add_3_9.INJECT1_1 = "NO" ;
    defparam Multiplier_0_add_3_9.INJECT1_0 = "NO" ;
    defparam Multiplier_0_add_3_9.INIT1 =  16'h66AA ;
    defparam Multiplier_0_add_3_9.INIT0 =  16'h66AA ;
    CCU2C Multiplier_0_add_3_9 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(f_s_Multiplier_0_1_19), 
        .B1(f_s_Multiplier_0_1_20), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co_Multiplier_0_3_8), .S0(s_Multiplier_0_3_19), 
        .S1(s_Multiplier_0_3_20), .COUT(co_Multiplier_0_3_9));

    defparam Multiplier_0_add_3_10.INJECT1_1 = "NO" ;
    defparam Multiplier_0_add_3_10.INJECT1_0 = "NO" ;
    defparam Multiplier_0_add_3_10.INIT1 =  16'h66AA ;
    defparam Multiplier_0_add_3_10.INIT0 =  16'h66AA ;
    CCU2C Multiplier_0_add_3_10 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(f_s_Multiplier_0_1_21), 
        .B1(scuba_vlo), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co_Multiplier_0_3_9), .S0(s_Multiplier_0_3_21), 
        .S1(s_Multiplier_0_3_22), .COUT(co_Multiplier_0_3_10));

    defparam Cadd_Multiplier_0_3_11.INJECT1_1 = "NO" ;
    defparam Cadd_Multiplier_0_3_11.INJECT1_0 = "NO" ;
    defparam Cadd_Multiplier_0_3_11.INIT1 =  16'h66AA ;
    defparam Cadd_Multiplier_0_3_11.INIT0 =  16'h66AA ;
    CCU2C Cadd_Multiplier_0_3_11 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo), 
        .B1(scuba_vlo), .C0(scuba_vhi), .C1(scuba_vhi), .D0(scuba_vhi), 
        .D1(scuba_vhi), .CIN(co_Multiplier_0_3_10), .S0(s_Multiplier_0_3_23), 
        .S1(), .COUT());

    defparam Cadd_t_Multiplier_0_4_1.INJECT1_1 = "NO" ;
    defparam Cadd_t_Multiplier_0_4_1.INJECT1_0 = "NO" ;
    defparam Cadd_t_Multiplier_0_4_1.INIT1 =  16'h66AA ;
    defparam Cadd_t_Multiplier_0_4_1.INIT0 =  16'h66AA ;
    CCU2C Cadd_t_Multiplier_0_4_1 (.A0(scuba_vlo), .A1(s_Multiplier_0_3_8), 
        .B0(scuba_vlo), .B1(f_Multiplier_0_pp_4_8), .C0(scuba_vhi), .C1(scuba_vhi), 
        .D0(scuba_vhi), .D1(scuba_vhi), .CIN(), .S0(), .S1(rego_o_8), .COUT(co_t_Multiplier_0_4_1));

    defparam t_Multiplier_0_add_4_2.INJECT1_1 = "NO" ;
    defparam t_Multiplier_0_add_4_2.INJECT1_0 = "NO" ;
    defparam t_Multiplier_0_add_4_2.INIT1 =  16'h66AA ;
    defparam t_Multiplier_0_add_4_2.INIT0 =  16'h66AA ;
    CCU2C t_Multiplier_0_add_4_2 (.A0(s_Multiplier_0_3_9), .A1(s_Multiplier_0_3_10), 
        .B0(f_Multiplier_0_pp_4_9), .B1(f_s_Multiplier_0_2_10), .C0(scuba_vhi), 
        .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), .CIN(co_t_Multiplier_0_4_1), 
        .S0(rego_o_9), .S1(rego_o_10), .COUT(co_t_Multiplier_0_4_2));

    defparam t_Multiplier_0_add_4_3.INJECT1_1 = "NO" ;
    defparam t_Multiplier_0_add_4_3.INJECT1_0 = "NO" ;
    defparam t_Multiplier_0_add_4_3.INIT1 =  16'h66AA ;
    defparam t_Multiplier_0_add_4_3.INIT0 =  16'h66AA ;
    CCU2C t_Multiplier_0_add_4_3 (.A0(s_Multiplier_0_3_11), .A1(s_Multiplier_0_3_12), 
        .B0(f_s_Multiplier_0_2_11), .B1(f_s_Multiplier_0_2_12), .C0(scuba_vhi), 
        .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), .CIN(co_t_Multiplier_0_4_2), 
        .S0(rego_o_11), .S1(rego_o_12), .COUT(co_t_Multiplier_0_4_3));

    defparam t_Multiplier_0_add_4_4.INJECT1_1 = "NO" ;
    defparam t_Multiplier_0_add_4_4.INJECT1_0 = "NO" ;
    defparam t_Multiplier_0_add_4_4.INIT1 =  16'h66AA ;
    defparam t_Multiplier_0_add_4_4.INIT0 =  16'h66AA ;
    CCU2C t_Multiplier_0_add_4_4 (.A0(s_Multiplier_0_3_13), .A1(s_Multiplier_0_3_14), 
        .B0(f_s_Multiplier_0_2_13), .B1(f_s_Multiplier_0_2_14), .C0(scuba_vhi), 
        .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), .CIN(co_t_Multiplier_0_4_3), 
        .S0(rego_o_13), .S1(rego_o_14), .COUT(co_t_Multiplier_0_4_4));

    defparam t_Multiplier_0_add_4_5.INJECT1_1 = "NO" ;
    defparam t_Multiplier_0_add_4_5.INJECT1_0 = "NO" ;
    defparam t_Multiplier_0_add_4_5.INIT1 =  16'h66AA ;
    defparam t_Multiplier_0_add_4_5.INIT0 =  16'h66AA ;
    CCU2C t_Multiplier_0_add_4_5 (.A0(s_Multiplier_0_3_15), .A1(s_Multiplier_0_3_16), 
        .B0(f_s_Multiplier_0_2_15), .B1(f_s_Multiplier_0_2_16), .C0(scuba_vhi), 
        .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), .CIN(co_t_Multiplier_0_4_4), 
        .S0(rego_o_15), .S1(rego_o_16), .COUT(co_t_Multiplier_0_4_5));

    defparam t_Multiplier_0_add_4_6.INJECT1_1 = "NO" ;
    defparam t_Multiplier_0_add_4_6.INJECT1_0 = "NO" ;
    defparam t_Multiplier_0_add_4_6.INIT1 =  16'h66AA ;
    defparam t_Multiplier_0_add_4_6.INIT0 =  16'h66AA ;
    CCU2C t_Multiplier_0_add_4_6 (.A0(s_Multiplier_0_3_17), .A1(s_Multiplier_0_3_18), 
        .B0(f_s_Multiplier_0_2_17), .B1(f_s_Multiplier_0_2_18), .C0(scuba_vhi), 
        .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), .CIN(co_t_Multiplier_0_4_5), 
        .S0(rego_o_17), .S1(rego_o_18), .COUT(co_t_Multiplier_0_4_6));

    defparam t_Multiplier_0_add_4_7.INJECT1_1 = "NO" ;
    defparam t_Multiplier_0_add_4_7.INJECT1_0 = "NO" ;
    defparam t_Multiplier_0_add_4_7.INIT1 =  16'h66AA ;
    defparam t_Multiplier_0_add_4_7.INIT0 =  16'h66AA ;
    CCU2C t_Multiplier_0_add_4_7 (.A0(s_Multiplier_0_3_19), .A1(s_Multiplier_0_3_20), 
        .B0(f_s_Multiplier_0_2_19), .B1(f_s_Multiplier_0_2_20), .C0(scuba_vhi), 
        .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), .CIN(co_t_Multiplier_0_4_6), 
        .S0(rego_o_19), .S1(rego_o_20), .COUT(co_t_Multiplier_0_4_7));

    defparam t_Multiplier_0_add_4_8.INJECT1_1 = "NO" ;
    defparam t_Multiplier_0_add_4_8.INJECT1_0 = "NO" ;
    defparam t_Multiplier_0_add_4_8.INIT1 =  16'h66AA ;
    defparam t_Multiplier_0_add_4_8.INIT0 =  16'h66AA ;
    CCU2C t_Multiplier_0_add_4_8 (.A0(s_Multiplier_0_3_21), .A1(s_Multiplier_0_3_22), 
        .B0(f_s_Multiplier_0_2_21), .B1(f_s_Multiplier_0_2_22), .C0(scuba_vhi), 
        .C1(scuba_vhi), .D0(scuba_vhi), .D1(scuba_vhi), .CIN(co_t_Multiplier_0_4_7), 
        .S0(rego_o_21), .S1(rego_o_22), .COUT(co_t_Multiplier_0_4_8));

    defparam t_Multiplier_0_add_4_9.INJECT1_1 = "NO" ;
    defparam t_Multiplier_0_add_4_9.INJECT1_0 = "NO" ;
    defparam t_Multiplier_0_add_4_9.INIT1 =  16'h66AA ;
    defparam t_Multiplier_0_add_4_9.INIT0 =  16'h66AA ;
    CCU2C t_Multiplier_0_add_4_9 (.A0(s_Multiplier_0_3_23), .A1(scuba_vlo), 
        .B0(f_s_Multiplier_0_2_23), .B1(scuba_vlo), .C0(scuba_vhi), .C1(scuba_vhi), 
        .D0(scuba_vhi), .D1(scuba_vhi), .CIN(co_t_Multiplier_0_4_8), .S0(rego_o_23), 
        .S1(), .COUT(co_t_Multiplier_0_4_9));

    defparam Multiplier_0_mult_0_0.INJECT1_1 = "NO" ;
    defparam Multiplier_0_mult_0_0.INJECT1_0 = "NO" ;
    defparam Multiplier_0_mult_0_0.INIT1 =  16'h7888 ;
    defparam Multiplier_0_mult_0_0.INIT0 =  16'h7888 ;
    CCU2C Multiplier_0_mult_0_0 (.A0(rega_a_0), .A1(rega_a_1), .B0(regb_b_1), 
        .B1(regb_b_1), .C0(rega_a_1), .C1(rega_a_2), .D0(regb_b_0), .D1(regb_b_0), 
        .CIN(Multiplier_0_cin_lr_0), .S0(Multiplier_0_pp_0_1), .S1(Multiplier_0_pp_0_2), 
        .COUT(mco));

    defparam Multiplier_0_mult_0_1.INJECT1_1 = "NO" ;
    defparam Multiplier_0_mult_0_1.INJECT1_0 = "NO" ;
    defparam Multiplier_0_mult_0_1.INIT1 =  16'h7888 ;
    defparam Multiplier_0_mult_0_1.INIT0 =  16'h7888 ;
    CCU2C Multiplier_0_mult_0_1 (.A0(rega_a_2), .A1(rega_a_3), .B0(regb_b_1), 
        .B1(regb_b_1), .C0(rega_a_3), .C1(rega_a_4), .D0(regb_b_0), .D1(regb_b_0), 
        .CIN(mco), .S0(Multiplier_0_pp_0_3), .S1(Multiplier_0_pp_0_4), .COUT(mco_1));

    defparam Multiplier_0_mult_0_2.INJECT1_1 = "NO" ;
    defparam Multiplier_0_mult_0_2.INJECT1_0 = "NO" ;
    defparam Multiplier_0_mult_0_2.INIT1 =  16'h7888 ;
    defparam Multiplier_0_mult_0_2.INIT0 =  16'h7888 ;
    CCU2C Multiplier_0_mult_0_2 (.A0(rega_a_4), .A1(rega_a_5), .B0(regb_b_1), 
        .B1(regb_b_1), .C0(rega_a_5), .C1(rega_a_6), .D0(regb_b_0), .D1(regb_b_0), 
        .CIN(mco_1), .S0(Multiplier_0_pp_0_5), .S1(Multiplier_0_pp_0_6), 
        .COUT(mco_2));

    defparam Multiplier_0_mult_0_3.INJECT1_1 = "NO" ;
    defparam Multiplier_0_mult_0_3.INJECT1_0 = "NO" ;
    defparam Multiplier_0_mult_0_3.INIT1 =  16'h7888 ;
    defparam Multiplier_0_mult_0_3.INIT0 =  16'h7888 ;
    CCU2C Multiplier_0_mult_0_3 (.A0(rega_a_6), .A1(rega_a_7), .B0(regb_b_1), 
        .B1(regb_b_1), .C0(rega_a_7), .C1(rega_a_8), .D0(regb_b_0), .D1(regb_b_0), 
        .CIN(mco_2), .S0(Multiplier_0_pp_0_7), .S1(Multiplier_0_pp_0_8), 
        .COUT(mco_3));

    defparam Multiplier_0_mult_0_4.INJECT1_1 = "NO" ;
    defparam Multiplier_0_mult_0_4.INJECT1_0 = "NO" ;
    defparam Multiplier_0_mult_0_4.INIT1 =  16'h7888 ;
    defparam Multiplier_0_mult_0_4.INIT0 =  16'h7888 ;
    CCU2C Multiplier_0_mult_0_4 (.A0(rega_a_8), .A1(rega_a_9), .B0(regb_b_1), 
        .B1(regb_b_1), .C0(rega_a_9), .C1(rega_a_10), .D0(regb_b_0), .D1(regb_b_0), 
        .CIN(mco_3), .S0(Multiplier_0_pp_0_9), .S1(Multiplier_0_pp_0_10), 
        .COUT(mco_4));

    defparam Multiplier_0_mult_0_5.INJECT1_1 = "NO" ;
    defparam Multiplier_0_mult_0_5.INJECT1_0 = "NO" ;
    defparam Multiplier_0_mult_0_5.INIT1 =  16'h7888 ;
    defparam Multiplier_0_mult_0_5.INIT0 =  16'h7888 ;
    CCU2C Multiplier_0_mult_0_5 (.A0(rega_a_10), .A1(Multiplier_0_mult_0_5_n1), 
        .B0(regb_b_1), .B1(scuba_vhi), .C0(Multiplier_0_mult_0_5_n2), .C1(scuba_vhi), 
        .D0(scuba_vhi), .D1(scuba_vhi), .CIN(mco_4), .S0(Multiplier_0_pp_0_11), 
        .S1(Multiplier_0_pp_0_12), .COUT(mfco));

    defparam Multiplier_0_mult_2_0.INJECT1_1 = "NO" ;
    defparam Multiplier_0_mult_2_0.INJECT1_0 = "NO" ;
    defparam Multiplier_0_mult_2_0.INIT1 =  16'h7888 ;
    defparam Multiplier_0_mult_2_0.INIT0 =  16'h7888 ;
    CCU2C Multiplier_0_mult_2_0 (.A0(rega_a_0), .A1(rega_a_1), .B0(regb_b_3), 
        .B1(regb_b_3), .C0(rega_a_1), .C1(rega_a_2), .D0(regb_b_2), .D1(regb_b_2), 
        .CIN(Multiplier_0_cin_lr_2), .S0(Multiplier_0_pp_1_3), .S1(Multiplier_0_pp_1_4), 
        .COUT(mco_5));

    defparam Multiplier_0_mult_2_1.INJECT1_1 = "NO" ;
    defparam Multiplier_0_mult_2_1.INJECT1_0 = "NO" ;
    defparam Multiplier_0_mult_2_1.INIT1 =  16'h7888 ;
    defparam Multiplier_0_mult_2_1.INIT0 =  16'h7888 ;
    CCU2C Multiplier_0_mult_2_1 (.A0(rega_a_2), .A1(rega_a_3), .B0(regb_b_3), 
        .B1(regb_b_3), .C0(rega_a_3), .C1(rega_a_4), .D0(regb_b_2), .D1(regb_b_2), 
        .CIN(mco_5), .S0(Multiplier_0_pp_1_5), .S1(Multiplier_0_pp_1_6), 
        .COUT(mco_6));

    defparam Multiplier_0_mult_2_2.INJECT1_1 = "NO" ;
    defparam Multiplier_0_mult_2_2.INJECT1_0 = "NO" ;
    defparam Multiplier_0_mult_2_2.INIT1 =  16'h7888 ;
    defparam Multiplier_0_mult_2_2.INIT0 =  16'h7888 ;
    CCU2C Multiplier_0_mult_2_2 (.A0(rega_a_4), .A1(rega_a_5), .B0(regb_b_3), 
        .B1(regb_b_3), .C0(rega_a_5), .C1(rega_a_6), .D0(regb_b_2), .D1(regb_b_2), 
        .CIN(mco_6), .S0(Multiplier_0_pp_1_7), .S1(Multiplier_0_pp_1_8), 
        .COUT(mco_7));

    defparam Multiplier_0_mult_2_3.INJECT1_1 = "NO" ;
    defparam Multiplier_0_mult_2_3.INJECT1_0 = "NO" ;
    defparam Multiplier_0_mult_2_3.INIT1 =  16'h7888 ;
    defparam Multiplier_0_mult_2_3.INIT0 =  16'h7888 ;
    CCU2C Multiplier_0_mult_2_3 (.A0(rega_a_6), .A1(rega_a_7), .B0(regb_b_3), 
        .B1(regb_b_3), .C0(rega_a_7), .C1(rega_a_8), .D0(regb_b_2), .D1(regb_b_2), 
        .CIN(mco_7), .S0(Multiplier_0_pp_1_9), .S1(Multiplier_0_pp_1_10), 
        .COUT(mco_8));

    defparam Multiplier_0_mult_2_4.INJECT1_1 = "NO" ;
    defparam Multiplier_0_mult_2_4.INJECT1_0 = "NO" ;
    defparam Multiplier_0_mult_2_4.INIT1 =  16'h7888 ;
    defparam Multiplier_0_mult_2_4.INIT0 =  16'h7888 ;
    CCU2C Multiplier_0_mult_2_4 (.A0(rega_a_8), .A1(rega_a_9), .B0(regb_b_3), 
        .B1(regb_b_3), .C0(rega_a_9), .C1(rega_a_10), .D0(regb_b_2), .D1(regb_b_2), 
        .CIN(mco_8), .S0(Multiplier_0_pp_1_11), .S1(Multiplier_0_pp_1_12), 
        .COUT(mco_9));

    defparam Multiplier_0_mult_2_5.INJECT1_1 = "NO" ;
    defparam Multiplier_0_mult_2_5.INJECT1_0 = "NO" ;
    defparam Multiplier_0_mult_2_5.INIT1 =  16'h7888 ;
    defparam Multiplier_0_mult_2_5.INIT0 =  16'h7888 ;
    CCU2C Multiplier_0_mult_2_5 (.A0(rega_a_10), .A1(Multiplier_0_mult_2_5_n1), 
        .B0(regb_b_3), .B1(scuba_vhi), .C0(Multiplier_0_mult_2_5_n2), .C1(scuba_vlo), 
        .D0(scuba_vhi), .D1(regb_b_2), .CIN(mco_9), .S0(Multiplier_0_pp_1_13), 
        .S1(Multiplier_0_pp_1_14), .COUT(mfco_1));

    defparam Multiplier_0_mult_4_0.INJECT1_1 = "NO" ;
    defparam Multiplier_0_mult_4_0.INJECT1_0 = "NO" ;
    defparam Multiplier_0_mult_4_0.INIT1 =  16'h7888 ;
    defparam Multiplier_0_mult_4_0.INIT0 =  16'h7888 ;
    CCU2C Multiplier_0_mult_4_0 (.A0(rega_a_0), .A1(rega_a_1), .B0(regb_b_5), 
        .B1(regb_b_5), .C0(rega_a_1), .C1(rega_a_2), .D0(regb_b_4), .D1(regb_b_4), 
        .CIN(Multiplier_0_cin_lr_4), .S0(Multiplier_0_pp_2_5), .S1(Multiplier_0_pp_2_6), 
        .COUT(mco_10));

    defparam Multiplier_0_mult_4_1.INJECT1_1 = "NO" ;
    defparam Multiplier_0_mult_4_1.INJECT1_0 = "NO" ;
    defparam Multiplier_0_mult_4_1.INIT1 =  16'h7888 ;
    defparam Multiplier_0_mult_4_1.INIT0 =  16'h7888 ;
    CCU2C Multiplier_0_mult_4_1 (.A0(rega_a_2), .A1(rega_a_3), .B0(regb_b_5), 
        .B1(regb_b_5), .C0(rega_a_3), .C1(rega_a_4), .D0(regb_b_4), .D1(regb_b_4), 
        .CIN(mco_10), .S0(Multiplier_0_pp_2_7), .S1(Multiplier_0_pp_2_8), 
        .COUT(mco_11));

    defparam Multiplier_0_mult_4_2.INJECT1_1 = "NO" ;
    defparam Multiplier_0_mult_4_2.INJECT1_0 = "NO" ;
    defparam Multiplier_0_mult_4_2.INIT1 =  16'h7888 ;
    defparam Multiplier_0_mult_4_2.INIT0 =  16'h7888 ;
    CCU2C Multiplier_0_mult_4_2 (.A0(rega_a_4), .A1(rega_a_5), .B0(regb_b_5), 
        .B1(regb_b_5), .C0(rega_a_5), .C1(rega_a_6), .D0(regb_b_4), .D1(regb_b_4), 
        .CIN(mco_11), .S0(Multiplier_0_pp_2_9), .S1(Multiplier_0_pp_2_10), 
        .COUT(mco_12));

    defparam Multiplier_0_mult_4_3.INJECT1_1 = "NO" ;
    defparam Multiplier_0_mult_4_3.INJECT1_0 = "NO" ;
    defparam Multiplier_0_mult_4_3.INIT1 =  16'h7888 ;
    defparam Multiplier_0_mult_4_3.INIT0 =  16'h7888 ;
    CCU2C Multiplier_0_mult_4_3 (.A0(rega_a_6), .A1(rega_a_7), .B0(regb_b_5), 
        .B1(regb_b_5), .C0(rega_a_7), .C1(rega_a_8), .D0(regb_b_4), .D1(regb_b_4), 
        .CIN(mco_12), .S0(Multiplier_0_pp_2_11), .S1(Multiplier_0_pp_2_12), 
        .COUT(mco_13));

    defparam Multiplier_0_mult_4_4.INJECT1_1 = "NO" ;
    defparam Multiplier_0_mult_4_4.INJECT1_0 = "NO" ;
    defparam Multiplier_0_mult_4_4.INIT1 =  16'h7888 ;
    defparam Multiplier_0_mult_4_4.INIT0 =  16'h7888 ;
    CCU2C Multiplier_0_mult_4_4 (.A0(rega_a_8), .A1(rega_a_9), .B0(regb_b_5), 
        .B1(regb_b_5), .C0(rega_a_9), .C1(rega_a_10), .D0(regb_b_4), .D1(regb_b_4), 
        .CIN(mco_13), .S0(Multiplier_0_pp_2_13), .S1(Multiplier_0_pp_2_14), 
        .COUT(mco_14));

    defparam Multiplier_0_mult_4_5.INJECT1_1 = "NO" ;
    defparam Multiplier_0_mult_4_5.INJECT1_0 = "NO" ;
    defparam Multiplier_0_mult_4_5.INIT1 =  16'h7888 ;
    defparam Multiplier_0_mult_4_5.INIT0 =  16'h7888 ;
    CCU2C Multiplier_0_mult_4_5 (.A0(rega_a_10), .A1(Multiplier_0_mult_4_5_n1), 
        .B0(regb_b_5), .B1(scuba_vhi), .C0(Multiplier_0_mult_4_5_n2), .C1(scuba_vlo), 
        .D0(scuba_vhi), .D1(regb_b_4), .CIN(mco_14), .S0(Multiplier_0_pp_2_15), 
        .S1(Multiplier_0_pp_2_16), .COUT(mfco_2));

    defparam Multiplier_0_mult_6_0.INJECT1_1 = "NO" ;
    defparam Multiplier_0_mult_6_0.INJECT1_0 = "NO" ;
    defparam Multiplier_0_mult_6_0.INIT1 =  16'h7888 ;
    defparam Multiplier_0_mult_6_0.INIT0 =  16'h7888 ;
    CCU2C Multiplier_0_mult_6_0 (.A0(rega_a_0), .A1(rega_a_1), .B0(regb_b_7), 
        .B1(regb_b_7), .C0(rega_a_1), .C1(rega_a_2), .D0(regb_b_6), .D1(regb_b_6), 
        .CIN(Multiplier_0_cin_lr_6), .S0(Multiplier_0_pp_3_7), .S1(Multiplier_0_pp_3_8), 
        .COUT(mco_15));

    defparam Multiplier_0_mult_6_1.INJECT1_1 = "NO" ;
    defparam Multiplier_0_mult_6_1.INJECT1_0 = "NO" ;
    defparam Multiplier_0_mult_6_1.INIT1 =  16'h7888 ;
    defparam Multiplier_0_mult_6_1.INIT0 =  16'h7888 ;
    CCU2C Multiplier_0_mult_6_1 (.A0(rega_a_2), .A1(rega_a_3), .B0(regb_b_7), 
        .B1(regb_b_7), .C0(rega_a_3), .C1(rega_a_4), .D0(regb_b_6), .D1(regb_b_6), 
        .CIN(mco_15), .S0(Multiplier_0_pp_3_9), .S1(Multiplier_0_pp_3_10), 
        .COUT(mco_16));

    defparam Multiplier_0_mult_6_2.INJECT1_1 = "NO" ;
    defparam Multiplier_0_mult_6_2.INJECT1_0 = "NO" ;
    defparam Multiplier_0_mult_6_2.INIT1 =  16'h7888 ;
    defparam Multiplier_0_mult_6_2.INIT0 =  16'h7888 ;
    CCU2C Multiplier_0_mult_6_2 (.A0(rega_a_4), .A1(rega_a_5), .B0(regb_b_7), 
        .B1(regb_b_7), .C0(rega_a_5), .C1(rega_a_6), .D0(regb_b_6), .D1(regb_b_6), 
        .CIN(mco_16), .S0(Multiplier_0_pp_3_11), .S1(Multiplier_0_pp_3_12), 
        .COUT(mco_17));

    defparam Multiplier_0_mult_6_3.INJECT1_1 = "NO" ;
    defparam Multiplier_0_mult_6_3.INJECT1_0 = "NO" ;
    defparam Multiplier_0_mult_6_3.INIT1 =  16'h7888 ;
    defparam Multiplier_0_mult_6_3.INIT0 =  16'h7888 ;
    CCU2C Multiplier_0_mult_6_3 (.A0(rega_a_6), .A1(rega_a_7), .B0(regb_b_7), 
        .B1(regb_b_7), .C0(rega_a_7), .C1(rega_a_8), .D0(regb_b_6), .D1(regb_b_6), 
        .CIN(mco_17), .S0(Multiplier_0_pp_3_13), .S1(Multiplier_0_pp_3_14), 
        .COUT(mco_18));

    defparam Multiplier_0_mult_6_4.INJECT1_1 = "NO" ;
    defparam Multiplier_0_mult_6_4.INJECT1_0 = "NO" ;
    defparam Multiplier_0_mult_6_4.INIT1 =  16'h7888 ;
    defparam Multiplier_0_mult_6_4.INIT0 =  16'h7888 ;
    CCU2C Multiplier_0_mult_6_4 (.A0(rega_a_8), .A1(rega_a_9), .B0(regb_b_7), 
        .B1(regb_b_7), .C0(rega_a_9), .C1(rega_a_10), .D0(regb_b_6), .D1(regb_b_6), 
        .CIN(mco_18), .S0(Multiplier_0_pp_3_15), .S1(Multiplier_0_pp_3_16), 
        .COUT(mco_19));

    defparam Multiplier_0_mult_6_5.INJECT1_1 = "NO" ;
    defparam Multiplier_0_mult_6_5.INJECT1_0 = "NO" ;
    defparam Multiplier_0_mult_6_5.INIT1 =  16'h7888 ;
    defparam Multiplier_0_mult_6_5.INIT0 =  16'h7888 ;
    CCU2C Multiplier_0_mult_6_5 (.A0(rega_a_10), .A1(Multiplier_0_mult_6_5_n1), 
        .B0(regb_b_7), .B1(scuba_vhi), .C0(Multiplier_0_mult_6_5_n2), .C1(scuba_vlo), 
        .D0(scuba_vhi), .D1(regb_b_6), .CIN(mco_19), .S0(Multiplier_0_pp_3_17), 
        .S1(Multiplier_0_pp_3_18), .COUT(mfco_3));

    defparam Multiplier_0_mult_8_0.INJECT1_1 = "NO" ;
    defparam Multiplier_0_mult_8_0.INJECT1_0 = "NO" ;
    defparam Multiplier_0_mult_8_0.INIT1 =  16'h7888 ;
    defparam Multiplier_0_mult_8_0.INIT0 =  16'h7888 ;
    CCU2C Multiplier_0_mult_8_0 (.A0(rega_a_0), .A1(rega_a_1), .B0(regb_b_9), 
        .B1(regb_b_9), .C0(rega_a_1), .C1(rega_a_2), .D0(regb_b_8), .D1(regb_b_8), 
        .CIN(Multiplier_0_cin_lr_8), .S0(Multiplier_0_pp_4_9), .S1(Multiplier_0_pp_4_10), 
        .COUT(mco_20));

    defparam Multiplier_0_mult_8_1.INJECT1_1 = "NO" ;
    defparam Multiplier_0_mult_8_1.INJECT1_0 = "NO" ;
    defparam Multiplier_0_mult_8_1.INIT1 =  16'h7888 ;
    defparam Multiplier_0_mult_8_1.INIT0 =  16'h7888 ;
    CCU2C Multiplier_0_mult_8_1 (.A0(rega_a_2), .A1(rega_a_3), .B0(regb_b_9), 
        .B1(regb_b_9), .C0(rega_a_3), .C1(rega_a_4), .D0(regb_b_8), .D1(regb_b_8), 
        .CIN(mco_20), .S0(Multiplier_0_pp_4_11), .S1(Multiplier_0_pp_4_12), 
        .COUT(mco_21));

    defparam Multiplier_0_mult_8_2.INJECT1_1 = "NO" ;
    defparam Multiplier_0_mult_8_2.INJECT1_0 = "NO" ;
    defparam Multiplier_0_mult_8_2.INIT1 =  16'h7888 ;
    defparam Multiplier_0_mult_8_2.INIT0 =  16'h7888 ;
    CCU2C Multiplier_0_mult_8_2 (.A0(rega_a_4), .A1(rega_a_5), .B0(regb_b_9), 
        .B1(regb_b_9), .C0(rega_a_5), .C1(rega_a_6), .D0(regb_b_8), .D1(regb_b_8), 
        .CIN(mco_21), .S0(Multiplier_0_pp_4_13), .S1(Multiplier_0_pp_4_14), 
        .COUT(mco_22));

    defparam Multiplier_0_mult_8_3.INJECT1_1 = "NO" ;
    defparam Multiplier_0_mult_8_3.INJECT1_0 = "NO" ;
    defparam Multiplier_0_mult_8_3.INIT1 =  16'h7888 ;
    defparam Multiplier_0_mult_8_3.INIT0 =  16'h7888 ;
    CCU2C Multiplier_0_mult_8_3 (.A0(rega_a_6), .A1(rega_a_7), .B0(regb_b_9), 
        .B1(regb_b_9), .C0(rega_a_7), .C1(rega_a_8), .D0(regb_b_8), .D1(regb_b_8), 
        .CIN(mco_22), .S0(Multiplier_0_pp_4_15), .S1(Multiplier_0_pp_4_16), 
        .COUT(mco_23));

    defparam Multiplier_0_mult_8_4.INJECT1_1 = "NO" ;
    defparam Multiplier_0_mult_8_4.INJECT1_0 = "NO" ;
    defparam Multiplier_0_mult_8_4.INIT1 =  16'h7888 ;
    defparam Multiplier_0_mult_8_4.INIT0 =  16'h7888 ;
    CCU2C Multiplier_0_mult_8_4 (.A0(rega_a_8), .A1(rega_a_9), .B0(regb_b_9), 
        .B1(regb_b_9), .C0(rega_a_9), .C1(rega_a_10), .D0(regb_b_8), .D1(regb_b_8), 
        .CIN(mco_23), .S0(Multiplier_0_pp_4_17), .S1(Multiplier_0_pp_4_18), 
        .COUT(mco_24));

    defparam Multiplier_0_mult_8_5.INJECT1_1 = "NO" ;
    defparam Multiplier_0_mult_8_5.INJECT1_0 = "NO" ;
    defparam Multiplier_0_mult_8_5.INIT1 =  16'h7888 ;
    defparam Multiplier_0_mult_8_5.INIT0 =  16'h7888 ;
    CCU2C Multiplier_0_mult_8_5 (.A0(rega_a_10), .A1(Multiplier_0_mult_8_5_n1), 
        .B0(regb_b_9), .B1(scuba_vhi), .C0(Multiplier_0_mult_8_5_n2), .C1(scuba_vlo), 
        .D0(scuba_vhi), .D1(regb_b_8), .CIN(mco_24), .S0(Multiplier_0_pp_4_19), 
        .S1(Multiplier_0_pp_4_20), .COUT(mfco_4));

    defparam Multiplier_0_mult_10_0.INJECT1_1 = "NO" ;
    defparam Multiplier_0_mult_10_0.INJECT1_0 = "NO" ;
    defparam Multiplier_0_mult_10_0.INIT1 =  16'h7888 ;
    defparam Multiplier_0_mult_10_0.INIT0 =  16'h7888 ;
    CCU2C Multiplier_0_mult_10_0 (.A0(Multiplier_0_mult_10_0_n0), .A1(Multiplier_0_mult_10_0_n1), 
        .B0(scuba_vhi), .B1(scuba_vhi), .C0(rega_a_1), .C1(rega_a_2), .D0(regb_b_10), 
        .D1(regb_b_10), .CIN(Multiplier_0_cin_lr_10), .S0(Multiplier_0_pp_5_11), 
        .S1(Multiplier_0_pp_5_12), .COUT(mco_25));

    defparam Multiplier_0_mult_10_1.INJECT1_1 = "NO" ;
    defparam Multiplier_0_mult_10_1.INJECT1_0 = "NO" ;
    defparam Multiplier_0_mult_10_1.INIT1 =  16'h7888 ;
    defparam Multiplier_0_mult_10_1.INIT0 =  16'h7888 ;
    CCU2C Multiplier_0_mult_10_1 (.A0(Multiplier_0_mult_10_1_n0), .A1(Multiplier_0_mult_10_1_n1), 
        .B0(scuba_vhi), .B1(scuba_vhi), .C0(rega_a_3), .C1(rega_a_4), .D0(regb_b_10), 
        .D1(regb_b_10), .CIN(mco_25), .S0(Multiplier_0_pp_5_13), .S1(Multiplier_0_pp_5_14), 
        .COUT(mco_26));

    defparam Multiplier_0_mult_10_2.INJECT1_1 = "NO" ;
    defparam Multiplier_0_mult_10_2.INJECT1_0 = "NO" ;
    defparam Multiplier_0_mult_10_2.INIT1 =  16'h7888 ;
    defparam Multiplier_0_mult_10_2.INIT0 =  16'h7888 ;
    CCU2C Multiplier_0_mult_10_2 (.A0(Multiplier_0_mult_10_2_n0), .A1(Multiplier_0_mult_10_2_n1), 
        .B0(scuba_vhi), .B1(scuba_vhi), .C0(rega_a_5), .C1(rega_a_6), .D0(regb_b_10), 
        .D1(regb_b_10), .CIN(mco_26), .S0(Multiplier_0_pp_5_15), .S1(Multiplier_0_pp_5_16), 
        .COUT(mco_27));

    defparam Multiplier_0_mult_10_3.INJECT1_1 = "NO" ;
    defparam Multiplier_0_mult_10_3.INJECT1_0 = "NO" ;
    defparam Multiplier_0_mult_10_3.INIT1 =  16'h7888 ;
    defparam Multiplier_0_mult_10_3.INIT0 =  16'h7888 ;
    CCU2C Multiplier_0_mult_10_3 (.A0(Multiplier_0_mult_10_3_n0), .A1(Multiplier_0_mult_10_3_n1), 
        .B0(scuba_vhi), .B1(scuba_vhi), .C0(rega_a_7), .C1(rega_a_8), .D0(regb_b_10), 
        .D1(regb_b_10), .CIN(mco_27), .S0(Multiplier_0_pp_5_17), .S1(Multiplier_0_pp_5_18), 
        .COUT(mco_28));

    defparam Multiplier_0_mult_10_4.INJECT1_1 = "NO" ;
    defparam Multiplier_0_mult_10_4.INJECT1_0 = "NO" ;
    defparam Multiplier_0_mult_10_4.INIT1 =  16'h7888 ;
    defparam Multiplier_0_mult_10_4.INIT0 =  16'h7888 ;
    CCU2C Multiplier_0_mult_10_4 (.A0(Multiplier_0_mult_10_4_n0), .A1(Multiplier_0_mult_10_4_n1), 
        .B0(scuba_vhi), .B1(scuba_vhi), .C0(rega_a_9), .C1(rega_a_10), .D0(regb_b_10), 
        .D1(regb_b_10), .CIN(mco_28), .S0(Multiplier_0_pp_5_19), .S1(Multiplier_0_pp_5_20), 
        .COUT(mco_29));

    VHI scuba_vhi_inst (.Z(scuba_vhi));

    VLO scuba_vlo_inst (.Z(scuba_vlo));

    defparam Multiplier_0_mult_10_5.INJECT1_1 = "NO" ;
    defparam Multiplier_0_mult_10_5.INJECT1_0 = "NO" ;
    defparam Multiplier_0_mult_10_5.INIT1 =  16'h7888 ;
    defparam Multiplier_0_mult_10_5.INIT0 =  16'h7888 ;
    CCU2C Multiplier_0_mult_10_5 (.A0(Multiplier_0_mult_10_5_n0), .A1(rega_a_11), 
        .B0(scuba_vhi), .B1(regb_b_11), .C0(Multiplier_0_mult_10_5_n2), 
        .C1(scuba_vlo), .D0(scuba_vhi), .D1(regb_b_10), .CIN(mco_29), .S0(Multiplier_0_pp_5_21), 
        .S1(Multiplier_0_pp_5_22), .COUT(mfco_5));

    assign rego_o_0 = f_Multiplier_0_pp_0_0;
    assign rego_o_1 = f_Multiplier_0_pp_0_1;
    assign rego_o_2 = f_s_Multiplier_0_0_2;
    assign rego_o_3 = f_s_Multiplier_0_0_3;
    assign rego_o_4 = s_Multiplier_0_3_4;
    assign rego_o_5 = s_Multiplier_0_3_5;
    assign rego_o_6 = s_Multiplier_0_3_6;
    assign rego_o_7 = s_Multiplier_0_3_7;


    // exemplar begin
    // exemplar attribute FF_99 GSR ENABLED
    // exemplar attribute FF_98 GSR ENABLED
    // exemplar attribute FF_97 GSR ENABLED
    // exemplar attribute FF_96 GSR ENABLED
    // exemplar attribute FF_95 GSR ENABLED
    // exemplar attribute FF_94 GSR ENABLED
    // exemplar attribute FF_93 GSR ENABLED
    // exemplar attribute FF_92 GSR ENABLED
    // exemplar attribute FF_91 GSR ENABLED
    // exemplar attribute FF_90 GSR ENABLED
    // exemplar attribute FF_89 GSR ENABLED
    // exemplar attribute FF_88 GSR ENABLED
    // exemplar attribute FF_87 GSR ENABLED
    // exemplar attribute FF_86 GSR ENABLED
    // exemplar attribute FF_85 GSR ENABLED
    // exemplar attribute FF_84 GSR ENABLED
    // exemplar attribute FF_83 GSR ENABLED
    // exemplar attribute FF_82 GSR ENABLED
    // exemplar attribute FF_81 GSR ENABLED
    // exemplar attribute FF_80 GSR ENABLED
    // exemplar attribute FF_79 GSR ENABLED
    // exemplar attribute FF_78 GSR ENABLED
    // exemplar attribute FF_77 GSR ENABLED
    // exemplar attribute FF_76 GSR ENABLED
    // exemplar attribute FF_75 GSR ENABLED
    // exemplar attribute FF_74 GSR ENABLED
    // exemplar attribute FF_73 GSR ENABLED
    // exemplar attribute FF_72 GSR ENABLED
    // exemplar attribute FF_71 GSR ENABLED
    // exemplar attribute FF_70 GSR ENABLED
    // exemplar attribute FF_69 GSR ENABLED
    // exemplar attribute FF_68 GSR ENABLED
    // exemplar attribute FF_67 GSR ENABLED
    // exemplar attribute FF_66 GSR ENABLED
    // exemplar attribute FF_65 GSR ENABLED
    // exemplar attribute FF_64 GSR ENABLED
    // exemplar attribute FF_63 GSR ENABLED
    // exemplar attribute FF_62 GSR ENABLED
    // exemplar attribute FF_61 GSR ENABLED
    // exemplar attribute FF_60 GSR ENABLED
    // exemplar attribute FF_59 GSR ENABLED
    // exemplar attribute FF_58 GSR ENABLED
    // exemplar attribute FF_57 GSR ENABLED
    // exemplar attribute FF_56 GSR ENABLED
    // exemplar attribute FF_55 GSR ENABLED
    // exemplar attribute FF_54 GSR ENABLED
    // exemplar attribute FF_53 GSR ENABLED
    // exemplar attribute FF_52 GSR ENABLED
    // exemplar attribute FF_51 GSR ENABLED
    // exemplar attribute FF_50 GSR ENABLED
    // exemplar attribute FF_49 GSR ENABLED
    // exemplar attribute FF_48 GSR ENABLED
    // exemplar attribute FF_47 GSR ENABLED
    // exemplar attribute FF_46 GSR ENABLED
    // exemplar attribute FF_45 GSR ENABLED
    // exemplar attribute FF_44 GSR ENABLED
    // exemplar attribute FF_43 GSR ENABLED
    // exemplar attribute FF_42 GSR ENABLED
    // exemplar attribute FF_41 GSR ENABLED
    // exemplar attribute FF_40 GSR ENABLED
    // exemplar attribute FF_39 GSR ENABLED
    // exemplar attribute FF_38 GSR ENABLED
    // exemplar attribute FF_37 GSR ENABLED
    // exemplar attribute FF_36 GSR ENABLED
    // exemplar attribute FF_35 GSR ENABLED
    // exemplar attribute FF_34 GSR ENABLED
    // exemplar attribute FF_33 GSR ENABLED
    // exemplar attribute FF_32 GSR ENABLED
    // exemplar attribute FF_31 GSR ENABLED
    // exemplar attribute FF_30 GSR ENABLED
    // exemplar attribute FF_29 GSR ENABLED
    // exemplar attribute FF_28 GSR ENABLED
    // exemplar attribute FF_27 GSR ENABLED
    // exemplar attribute FF_26 GSR ENABLED
    // exemplar attribute FF_25 GSR ENABLED
    // exemplar attribute FF_24 GSR ENABLED
    // exemplar attribute FF_23 GSR ENABLED
    // exemplar attribute FF_22 GSR ENABLED
    // exemplar attribute FF_21 GSR ENABLED
    // exemplar attribute FF_20 GSR ENABLED
    // exemplar attribute FF_19 GSR ENABLED
    // exemplar attribute FF_18 GSR ENABLED
    // exemplar attribute FF_17 GSR ENABLED
    // exemplar attribute FF_16 GSR ENABLED
    // exemplar attribute FF_15 GSR ENABLED
    // exemplar attribute FF_14 GSR ENABLED
    // exemplar attribute FF_13 GSR ENABLED
    // exemplar attribute FF_12 GSR ENABLED
    // exemplar attribute FF_11 GSR ENABLED
    // exemplar attribute FF_10 GSR ENABLED
    // exemplar attribute FF_9 GSR ENABLED
    // exemplar attribute FF_8 GSR ENABLED
    // exemplar attribute FF_7 GSR ENABLED
    // exemplar attribute FF_6 GSR ENABLED
    // exemplar attribute FF_5 GSR ENABLED
    // exemplar attribute FF_4 GSR ENABLED
    // exemplar attribute FF_3 GSR ENABLED
    // exemplar attribute FF_2 GSR ENABLED
    // exemplar attribute FF_1 GSR ENABLED
    // exemplar attribute FF_0 GSR ENABLED
    // exemplar end

endmodule
