/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.13.0.56.2 */
/* Module Version: 1.6 */
/* Wed Feb 28 16:19:56 2024 */

/* parameterized module instance */
SinCos __ (.Clock( ), .ClkEn( ), .Reset( ), .Theta( ), .Sine( ), 
    .Cosine( ));
