/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.13.0.56.2 */
/* Module Version: 5.7 */
/* Thu Feb 29 19:39:22 2024 */

/* parameterized module instance */
PLL __ (.CLKI( ), .CLKOP( ));
