/* Generated by Amaranth Yosys 0.40 (PyPI ver 0.40.0.0.post93, git sha1 a1bb0255d) */

(* top =  1  *)
(* src = "/home/user/SDR-HLS/HLSImplementation/CIC/CIC.py:19" *)
(* generator = "Amaranth" *)
module top(gain, d_in, \clk$5 , rst, d_out, d_clk, clk);
  reg \$auto$verilog_backend.cc:2352:dump_module$1  = 0;
  wire [64:0] \$1 ;
  wire [64:0] \$10 ;
  wire [64:0] \$11 ;
  wire [64:0] \$12 ;
  wire [64:0] \$13 ;
  wire [64:0] \$14 ;
  wire [8:0] \$15 ;
  wire [63:0] \$16 ;
  reg [63:0] \$17 ;
  reg [63:0] \$18 ;
  reg [63:0] \$19 ;
  wire [64:0] \$2 ;
  reg [63:0] \$20 ;
  reg [63:0] \$21 ;
  reg [15:0] \$22 ;
  reg [63:0] \$23 ;
  reg \$24 ;
  reg \$25 ;
  reg \$26 ;
  reg [63:0] \$27 ;
  reg [63:0] \$28 ;
  reg [63:0] \$29 ;
  wire [64:0] \$3 ;
  reg [63:0] \$30 ;
  reg [63:0] \$31 ;
  reg [63:0] \$32 ;
  reg [63:0] \$33 ;
  reg [63:0] \$34 ;
  reg [63:0] \$35 ;
  reg [63:0] \$36 ;
  reg [63:0] \$37 ;
  reg [11:0] \$38 ;
  wire [64:0] \$4 ;
  wire [64:0] \$5 ;
  wire \$6 ;
  wire \$7 ;
  wire [16:0] \$8 ;
  wire [16:0] \$9 ;
  (* src = "/home/user/SDR-HLS/HLSImplementation/CIC/CIC.py:11" *)
  input clk;
  wire clk;
  (* src = "/home/user/.local/lib/python3.10/site-packages/amaranth/hdl/_ir.py:270" *)
  input \clk$5 ;
  wire \clk$5 ;
  (* src = "/home/user/.local/lib/python3.10/site-packages/amaranth/hdl/_ir.py:270" *)
  wire \clk$7 ;
  (* src = "/home/user/SDR-HLS/HLSImplementation/CIC/CIC.py:46" *)
  reg [15:0] count = 16'h0000;
  (* src = "/home/user/SDR-HLS/HLSImplementation/CIC/CIC.py:28" *)
  reg [63:0] d1 = 64'h0000000000000000;
  (* src = "/home/user/SDR-HLS/HLSImplementation/CIC/CIC.py:43" *)
  reg [63:0] d10 = 64'h0000000000000000;
  (* src = "/home/user/SDR-HLS/HLSImplementation/CIC/CIC.py:29" *)
  reg [63:0] d2 = 64'h0000000000000000;
  (* src = "/home/user/SDR-HLS/HLSImplementation/CIC/CIC.py:30" *)
  reg [63:0] d3 = 64'h0000000000000000;
  (* src = "/home/user/SDR-HLS/HLSImplementation/CIC/CIC.py:31" *)
  reg [63:0] d4 = 64'h0000000000000000;
  (* src = "/home/user/SDR-HLS/HLSImplementation/CIC/CIC.py:32" *)
  reg [63:0] d5 = 64'h0000000000000000;
  (* src = "/home/user/SDR-HLS/HLSImplementation/CIC/CIC.py:35" *)
  reg [63:0] d6 = 64'h0000000000000000;
  (* src = "/home/user/SDR-HLS/HLSImplementation/CIC/CIC.py:37" *)
  reg [63:0] d7 = 64'h0000000000000000;
  (* src = "/home/user/SDR-HLS/HLSImplementation/CIC/CIC.py:39" *)
  reg [63:0] d8 = 64'h0000000000000000;
  (* src = "/home/user/SDR-HLS/HLSImplementation/CIC/CIC.py:41" *)
  reg [63:0] d9 = 64'h0000000000000000;
  (* src = "/home/user/SDR-HLS/HLSImplementation/CIC/CIC.py:16" *)
  output d_clk;
  reg d_clk = 1'h0;
  (* src = "/home/user/SDR-HLS/HLSImplementation/CIC/CIC.py:49" *)
  reg d_clk_tmp = 1'h0;
  (* src = "/home/user/SDR-HLS/HLSImplementation/CIC/CIC.py:36" *)
  reg [63:0] d_d6 = 64'h0000000000000000;
  (* src = "/home/user/SDR-HLS/HLSImplementation/CIC/CIC.py:38" *)
  reg [63:0] d_d7 = 64'h0000000000000000;
  (* src = "/home/user/SDR-HLS/HLSImplementation/CIC/CIC.py:40" *)
  reg [63:0] d_d8 = 64'h0000000000000000;
  (* src = "/home/user/SDR-HLS/HLSImplementation/CIC/CIC.py:42" *)
  reg [63:0] d_d9 = 64'h0000000000000000;
  (* src = "/home/user/SDR-HLS/HLSImplementation/CIC/CIC.py:25" *)
  reg [63:0] d_d_tmp = 64'h0000000000000000;
  (* src = "/home/user/SDR-HLS/HLSImplementation/CIC/CIC.py:13" *)
  input [11:0] d_in;
  wire [11:0] d_in;
  (* src = "/home/user/SDR-HLS/HLSImplementation/CIC/CIC.py:15" *)
  output [11:0] d_out;
  reg [11:0] d_out = 12'h000;
  (* src = "/home/user/SDR-HLS/HLSImplementation/CIC/CIC.py:45" *)
  reg [63:0] d_scaled = 64'h0000000000000000;
  (* src = "/home/user/SDR-HLS/HLSImplementation/CIC/CIC.py:24" *)
  reg [63:0] d_tmp = 64'h0000000000000000;
  (* src = "/home/user/SDR-HLS/HLSImplementation/CIC/CIC.py:12" *)
  input [7:0] gain;
  wire [7:0] gain;
  (* src = "/home/user/.local/lib/python3.10/site-packages/amaranth/hdl/_ir.py:270" *)
  input rst;
  wire rst;
  (* src = "/home/user/SDR-HLS/HLSImplementation/CIC/CIC.py:48" *)
  reg v_comb = 1'h0;
  assign \$1  = $signed(d_in) + (* src = "/home/user/SDR-HLS/HLSImplementation/CIC/CIC.py:54" *) $signed(d1);
  assign \$2  = $signed(d1) + (* src = "/home/user/SDR-HLS/HLSImplementation/CIC/CIC.py:55" *) $signed(d2);
  assign \$3  = $signed(d2) + (* src = "/home/user/SDR-HLS/HLSImplementation/CIC/CIC.py:56" *) $signed(d3);
  assign \$4  = $signed(d3) + (* src = "/home/user/SDR-HLS/HLSImplementation/CIC/CIC.py:57" *) $signed(d4);
  assign \$5  = $signed(d4) + (* src = "/home/user/SDR-HLS/HLSImplementation/CIC/CIC.py:58" *) $signed(d5);
  assign \$6  = count == (* src = "/home/user/SDR-HLS/HLSImplementation/CIC/CIC.py:62" *) 4'hf;
  assign \$7  = count == (* src = "/home/user/SDR-HLS/HLSImplementation/CIC/CIC.py:70" *) 4'h8;
  assign \$8  = count + (* src = "/home/user/SDR-HLS/HLSImplementation/CIC/CIC.py:73" *) 1'h1;
  assign \$9  = count + (* src = "/home/user/SDR-HLS/HLSImplementation/CIC/CIC.py:78" *) 1'h1;
  assign \$10  = $signed(d_tmp) - (* src = "/home/user/SDR-HLS/HLSImplementation/CIC/CIC.py:89" *) $signed(d_d_tmp);
  assign \$11  = $signed(d6) - (* src = "/home/user/SDR-HLS/HLSImplementation/CIC/CIC.py:92" *) $signed(d_d6);
  assign \$12  = $signed(d7) - (* src = "/home/user/SDR-HLS/HLSImplementation/CIC/CIC.py:95" *) $signed(d_d7);
  assign \$13  = $signed(d8) - (* src = "/home/user/SDR-HLS/HLSImplementation/CIC/CIC.py:98" *) $signed(d_d8);
  assign \$14  = $signed(d9) - (* src = "/home/user/SDR-HLS/HLSImplementation/CIC/CIC.py:101" *) $signed(d_d9);
  assign \$15  = 6'h34 - (* src = "/home/user/SDR-HLS/HLSImplementation/CIC/CIC.py:105" *) gain;
  assign \$16  = $signed(d10) >>> (* src = "/home/user/SDR-HLS/HLSImplementation/CIC/CIC.py:105" *) \$15 ;
  (* src = "/home/user/SDR-HLS/HLSImplementation/CIC/CIC.py:28" *)
  always @(posedge \clk$5 )
    d1 <= \$17 ;
  (* src = "/home/user/SDR-HLS/HLSImplementation/CIC/CIC.py:29" *)
  always @(posedge \clk$5 )
    d2 <= \$18 ;
  (* src = "/home/user/SDR-HLS/HLSImplementation/CIC/CIC.py:30" *)
  always @(posedge \clk$5 )
    d3 <= \$19 ;
  (* src = "/home/user/SDR-HLS/HLSImplementation/CIC/CIC.py:31" *)
  always @(posedge \clk$5 )
    d4 <= \$20 ;
  (* src = "/home/user/SDR-HLS/HLSImplementation/CIC/CIC.py:32" *)
  always @(posedge \clk$5 )
    d5 <= \$21 ;
  (* src = "/home/user/SDR-HLS/HLSImplementation/CIC/CIC.py:46" *)
  always @(posedge \clk$5 )
    count <= \$22 ;
  (* src = "/home/user/SDR-HLS/HLSImplementation/CIC/CIC.py:24" *)
  always @(posedge \clk$5 )
    d_tmp <= \$23 ;
  (* src = "/home/user/SDR-HLS/HLSImplementation/CIC/CIC.py:49" *)
  always @(posedge \clk$5 )
    d_clk_tmp <= \$24 ;
  (* src = "/home/user/SDR-HLS/HLSImplementation/CIC/CIC.py:48" *)
  always @(posedge \clk$5 )
    v_comb <= \$25 ;
  (* src = "/home/user/SDR-HLS/HLSImplementation/CIC/CIC.py:16" *)
  always @(posedge \clk$5 )
    d_clk <= \$26 ;
  (* src = "/home/user/SDR-HLS/HLSImplementation/CIC/CIC.py:25" *)
  always @(posedge \clk$5 )
    d_d_tmp <= \$27 ;
  (* src = "/home/user/SDR-HLS/HLSImplementation/CIC/CIC.py:35" *)
  always @(posedge \clk$5 )
    d6 <= \$28 ;
  (* src = "/home/user/SDR-HLS/HLSImplementation/CIC/CIC.py:36" *)
  always @(posedge \clk$5 )
    d_d6 <= \$29 ;
  (* src = "/home/user/SDR-HLS/HLSImplementation/CIC/CIC.py:37" *)
  always @(posedge \clk$5 )
    d7 <= \$30 ;
  (* src = "/home/user/SDR-HLS/HLSImplementation/CIC/CIC.py:38" *)
  always @(posedge \clk$5 )
    d_d7 <= \$31 ;
  (* src = "/home/user/SDR-HLS/HLSImplementation/CIC/CIC.py:39" *)
  always @(posedge \clk$5 )
    d8 <= \$32 ;
  (* src = "/home/user/SDR-HLS/HLSImplementation/CIC/CIC.py:40" *)
  always @(posedge \clk$5 )
    d_d8 <= \$33 ;
  (* src = "/home/user/SDR-HLS/HLSImplementation/CIC/CIC.py:41" *)
  always @(posedge \clk$5 )
    d9 <= \$34 ;
  (* src = "/home/user/SDR-HLS/HLSImplementation/CIC/CIC.py:42" *)
  always @(posedge \clk$5 )
    d_d9 <= \$35 ;
  (* src = "/home/user/SDR-HLS/HLSImplementation/CIC/CIC.py:43" *)
  always @(posedge \clk$5 )
    d10 <= \$36 ;
  (* src = "/home/user/SDR-HLS/HLSImplementation/CIC/CIC.py:45" *)
  always @(posedge \clk$5 )
    d_scaled <= \$37 ;
  (* src = "/home/user/SDR-HLS/HLSImplementation/CIC/CIC.py:15" *)
  always @(posedge \clk$5 )
    d_out <= \$38 ;
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$1 ) begin end
    \$17  = \$1 [63:0];
    if (rst) begin
      \$17  = 64'h0000000000000000;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$1 ) begin end
    \$18  = \$2 [63:0];
    if (rst) begin
      \$18  = 64'h0000000000000000;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$1 ) begin end
    \$19  = \$3 [63:0];
    if (rst) begin
      \$19  = 64'h0000000000000000;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$1 ) begin end
    \$20  = \$4 [63:0];
    if (rst) begin
      \$20  = 64'h0000000000000000;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$1 ) begin end
    \$21  = \$5 [63:0];
    if (rst) begin
      \$21  = 64'h0000000000000000;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    if (\$6 ) begin
      \$22  = 16'h0000;
    end else if (\$7 ) begin
      \$22  = \$8 [15:0];
    end else begin
      \$22  = \$9 [15:0];
    end
    if (rst) begin
      \$22  = 16'h0000;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$1 ) begin end
    \$23  = d_tmp;
    if (\$6 ) begin
      \$23  = d5;
    end
    if (rst) begin
      \$23  = 64'h0000000000000000;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$1 ) begin end
    \$24  = d_clk_tmp;
    if (\$6 ) begin
      \$24  = 1'h1;
    end else if (\$7 ) begin
      \$24  = 1'h0;
    end
    if (rst) begin
      \$24  = 1'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    if (\$6 ) begin
      \$25  = 1'h1;
    end else if (\$7 ) begin
      \$25  = 1'h0;
    end else begin
      \$25  = 1'h0;
    end
    if (rst) begin
      \$25  = 1'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$1 ) begin end
    \$26  = d_clk_tmp;
    if (rst) begin
      \$26  = 1'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$1 ) begin end
    \$27  = d_d_tmp;
    if (v_comb) begin
      \$27  = d_tmp;
    end
    if (rst) begin
      \$27  = 64'h0000000000000000;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$1 ) begin end
    \$28  = d6;
    if (v_comb) begin
      \$28  = \$10 [63:0];
    end
    if (rst) begin
      \$28  = 64'h0000000000000000;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$1 ) begin end
    \$29  = d_d6;
    if (v_comb) begin
      \$29  = d6;
    end
    if (rst) begin
      \$29  = 64'h0000000000000000;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$1 ) begin end
    \$30  = d7;
    if (v_comb) begin
      \$30  = \$11 [63:0];
    end
    if (rst) begin
      \$30  = 64'h0000000000000000;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$1 ) begin end
    \$31  = d_d7;
    if (v_comb) begin
      \$31  = d7;
    end
    if (rst) begin
      \$31  = 64'h0000000000000000;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$1 ) begin end
    \$32  = d8;
    if (v_comb) begin
      \$32  = \$12 [63:0];
    end
    if (rst) begin
      \$32  = 64'h0000000000000000;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$1 ) begin end
    \$33  = d_d8;
    if (v_comb) begin
      \$33  = d8;
    end
    if (rst) begin
      \$33  = 64'h0000000000000000;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$1 ) begin end
    \$34  = d9;
    if (v_comb) begin
      \$34  = \$13 [63:0];
    end
    if (rst) begin
      \$34  = 64'h0000000000000000;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$1 ) begin end
    \$35  = d_d9;
    if (v_comb) begin
      \$35  = d9;
    end
    if (rst) begin
      \$35  = 64'h0000000000000000;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$1 ) begin end
    \$36  = d10;
    if (v_comb) begin
      \$36  = \$14 [63:0];
    end
    if (rst) begin
      \$36  = 64'h0000000000000000;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$1 ) begin end
    \$37  = d_scaled;
    if (v_comb) begin
      \$37  = d10;
    end
    if (rst) begin
      \$37  = 64'h0000000000000000;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$1 ) begin end
    \$38  = d_out;
    if (v_comb) begin
      \$38  = \$16 [11:0];
    end
    if (rst) begin
      \$38  = 12'h000;
    end
  end
  assign \clk$7  = \clk$5 ;
endmodule
