# Include the general configuration file
include ../config.mk

# Verilog sources
VERILOG_SOURCES += hdl/Mixer.v

# VHDL sources (if any)
VHDL_SOURCES = 

# Top-level module name
TOPLEVEL = Mixer

# Python test module(s)
MODULE = Mixer_tb

