# Include the general configuration file
include ../config.mk

# Verilog sources
VERILOG_SOURCES += hdl/PWM.v

# VHDL sources (if any)
VHDL_SOURCES = 

# Top-level module name
TOPLEVEL = PWM

# Python test module(s)
MODULE = PWM_tb

