# Include the general configuration file
include ../config.mk

# Verilog sources
VERILOG_SOURCES += hdl/NCO.v

# VHDL sources (if any)
VHDL_SOURCES = 

# Top-level module name
TOPLEVEL = nco_sig

# Python test module(s)
MODULE = NCO_tb

