# Include the general configuration file
include ../config.mk

# Verilog sources
VERILOG_SOURCES += hdl/CIC.v

# VHDL sources (if any)
VHDL_SOURCES = 

# Top-level module name
TOPLEVEL = CIC

# Python test module(s)
MODULE = CIC_tb

