/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.13.0.56.2 */
/* Module Version: 5.7 */
/* Mon Aug 26 01:04:54 2024 */

/* parameterized module instance */
PLL __ (.CLKI( ), .CLKOP( ));
