# Include the general configuration file
include ../config.mk

# Verilog sources
VERILOG_SOURCES += hdl/AMDemod.v

# VHDL sources (if any)
VHDL_SOURCES = 

# Top-level module name
TOPLEVEL = AMDemodulator

# Python test module(s)
MODULE = AMDemod_tb

