/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.13.0.56.2 */
/* Module Version: 4.9 */
/* Mon Aug 26 01:00:27 2024 */

/* parameterized module instance */
Multiplier __ (.Clock( ), .ClkEn( ), .Aclr( ), .DataA( ), .DataB( ), 
    .Result( ));
