/* Generated by Yosys 0.42+40 (git sha1 a739e21a5, clang++ 14.0.0-1ubuntu1.1 -fPIC -Os) */

(* top =  1  *)
(* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/sequential/amaranth/sqrt_sequential.py:52" *)
(* generator = "Amaranth" *)
module top(valid, clk, rst, res, ready, current_count, q, r, r_reg, left, right, a, sqrt_state, num);
  reg \$auto$verilog_backend.cc:2352:dump_module$1  = 0;
  wire \$1 ;
  reg [31:0] \$10 ;
  reg \$11 ;
  reg [15:0] \$12 ;
  reg [17:0] \$13 ;
  reg [3:0] \$14 ;
  wire \$2 ;
  wire \$3 ;
  wire \$4 ;
  wire [4:0] \$5 ;
  wire \$6 ;
  wire [18:0] \$7 ;
  wire [18:0] \$8 ;
  reg [1:0] \$9 ;
  (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/sequential/amaranth/sqrt_sequential.py:42" *)
  output [31:0] a;
  reg [31:0] a = 32'd0;
  (* src = "/home/user/FPGA/tools/amaranth/amaranth/hdl/_ir.py:215" *)
  input clk;
  wire clk;
  (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/sequential/amaranth/sqrt_sequential.py:40" *)
  output [3:0] current_count;
  reg [3:0] current_count = 4'h0;
  (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/sequential/amaranth/sqrt_sequential.py:44" *)
  output [17:0] left;
  wire [17:0] left;
  (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/sequential/amaranth/sqrt_sequential.py:31" *)
  input [31:0] num;
  wire [31:0] num;
  (* init = 16'h0000 *)
  (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/sequential/amaranth/sqrt_sequential.py:43" *)
  output [15:0] q;
  wire [15:0] q;
  (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/sequential/amaranth/sqrt_sequential.py:46" *)
  output [17:0] r;
  reg [17:0] r;
  (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/sequential/amaranth/sqrt_sequential.py:47" *)
  output [17:0] r_reg;
  reg [17:0] r_reg = 18'h00000;
  (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/sequential/amaranth/sqrt_sequential.py:37" *)
  output ready;
  reg ready = 1'h0;
  (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/sequential/amaranth/sqrt_sequential.py:43" *)
  output [15:0] res;
  reg [15:0] res = 16'h0000;
  (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/sequential/amaranth/sqrt_sequential.py:32" *)
  wire reset;
  (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/sequential/amaranth/sqrt_sequential.py:45" *)
  output [17:0] right;
  wire [17:0] right;
  (* src = "/home/user/FPGA/tools/amaranth/amaranth/hdl/_ir.py:215" *)
  input rst;
  wire rst;
  (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/sequential/amaranth/sqrt_sequential.py:41" *)
  output [1:0] sqrt_state;
  reg [1:0] sqrt_state = 2'h0;
  (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/sequential/amaranth/sqrt_sequential.py:33" *)
  input valid;
  wire valid;
  assign \$2  = & (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/sequential/amaranth/sqrt_sequential.py:91" *) current_count;
  assign \$4  = sqrt_state == (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/sequential/amaranth/sqrt_sequential.py:114" *) 1'h1;
  assign \$5  = current_count + (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/sequential/amaranth/sqrt_sequential.py:116" *) 1'h1;
  assign \$6  = ~ (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/sequential/amaranth/sqrt_sequential.py:118" *) r[17];
  assign \$7  = { r_reg[15:0], a[31:30] } + (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/sequential/amaranth/sqrt_sequential.py:124" *) { res, r_reg[17], 1'h1 };
  assign \$8  = { r_reg[15:0], a[31:30] } - (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/sequential/amaranth/sqrt_sequential.py:126" *) { res, r_reg[17], 1'h1 };
  (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/sequential/amaranth/sqrt_sequential.py:41" *)
  always @(posedge clk)
    sqrt_state <= \$9 ;
  (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/sequential/amaranth/sqrt_sequential.py:42" *)
  always @(posedge clk)
    a <= \$10 ;
  (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/sequential/amaranth/sqrt_sequential.py:37" *)
  always @(posedge clk)
    ready <= \$11 ;
  (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/sequential/amaranth/sqrt_sequential.py:43" *)
  always @(posedge clk)
    res <= \$12 ;
  (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/sequential/amaranth/sqrt_sequential.py:47" *)
  always @(posedge clk)
    r_reg <= \$13 ;
  (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/sequential/amaranth/sqrt_sequential.py:40" *)
  always @(posedge clk)
    current_count <= \$14 ;
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$1 ) begin end
    \$9  = sqrt_state;
    (* full_case = 32'd1 *)
    if (\$1 ) begin
      \$9  = 2'h0;
    end else begin
      (* full_case = 32'd1 *)
      casez (sqrt_state)
        2'h0:
            if (valid) begin
              \$9  = 2'h1;
            end
        2'h1:
            if (\$2 ) begin
              \$9  = 2'h2;
            end
        2'h2:
            \$9  = 2'h0;
        default:
            \$9  = 2'h0;
      endcase
    end
    if (rst) begin
      \$9  = 2'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$1 ) begin end
    \$10  = a;
    (* full_case = 32'd1 *)
    if (\$1 ) begin
    end else begin
      casez (sqrt_state)
        2'h0:
            if (valid) begin
              \$10  = num;
            end
        2'h1:
            /* empty */;
        2'h2:
            \$10  = 32'd0;
      endcase
    end
    (* full_case = 32'd1 *)
    if (\$3 ) begin
      \$10  = 32'd0;
    end else begin
      if (\$4 ) begin
        \$10  = { a[29:0], 2'h0 };
      end
    end
    if (rst) begin
      \$10  = 32'd0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$1 ) begin end
    \$11  = ready;
    (* full_case = 32'd1 *)
    if (\$1 ) begin
    end else begin
      casez (sqrt_state)
        2'h0:
            /* empty */;
        2'h1:
            if (\$2 ) begin
              \$11  = 1'h1;
            end
        2'h2:
            \$11  = 1'h0;
      endcase
    end
    if (rst) begin
      \$11  = 1'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$1 ) begin end
    \$12  = res;
    (* full_case = 32'd1 *)
    if (\$1 ) begin
    end else begin
      casez (sqrt_state)
        2'h0:
            /* empty */;
        2'h1:
            /* empty */;
        2'h2:
            \$12  = 16'h0000;
      endcase
    end
    (* full_case = 32'd1 *)
    if (\$3 ) begin
      \$12  = 16'h0000;
    end else begin
      if (\$4 ) begin
        \$12  = { res[14:0], \$6  };
      end
    end
    if (rst) begin
      \$12  = 16'h0000;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$1 ) begin end
    \$13  = r_reg;
    (* full_case = 32'd1 *)
    if (\$1 ) begin
    end else begin
      casez (sqrt_state)
        2'h0:
            /* empty */;
        2'h1:
            /* empty */;
        2'h2:
            \$13  = 18'h00000;
      endcase
    end
    (* full_case = 32'd1 *)
    if (\$3 ) begin
      \$13  = 18'h00000;
    end else begin
      if (\$4 ) begin
        \$13  = r;
      end
    end
    if (rst) begin
      \$13  = 18'h00000;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$1 ) begin end
    \$14  = current_count;
    (* full_case = 32'd1 *)
    if (\$1 ) begin
    end else begin
      casez (sqrt_state)
        2'h0:
            /* empty */;
        2'h1:
            /* empty */;
        2'h2:
            \$14  = 4'h0;
      endcase
    end
    (* full_case = 32'd1 *)
    if (\$3 ) begin
      \$14  = 4'h0;
    end else begin
      if (\$4 ) begin
        \$14  = \$5 [3:0];
      end
    end
    if (rst) begin
      \$14  = 4'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    if (r_reg[17]) begin
      r = \$7 [17:0];
    end else begin
      r = \$8 [17:0];
    end
  end
  assign reset = 1'h0;
  assign q = res;
  assign left = { r_reg[15:0], a[31:30] };
  assign right = { res, r_reg[17], 1'h1 };
  assign \$1  = 1'h1;
  assign \$3  = 1'h1;
endmodule
