/* Generated by Yosys 0.42+40 (git sha1 a739e21a5, clang++ 14.0.0-1ubuntu1.1 -fPIC -Os) */

(* top =  1  *)
(* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:40" *)
(* generator = "Amaranth" *)
module top(result, num);
  reg \$auto$verilog_backend.cc:2352:dump_module$1  = 0;
  wire \$1 ;
  wire [18:0] \$10 ;
  wire [18:0] \$11 ;
  wire \$12 ;
  wire \$13 ;
  wire [18:0] \$14 ;
  wire [18:0] \$15 ;
  wire \$16 ;
  wire \$17 ;
  wire [18:0] \$18 ;
  wire [18:0] \$19 ;
  wire [18:0] \$2 ;
  wire \$20 ;
  wire \$21 ;
  wire [18:0] \$22 ;
  wire [18:0] \$23 ;
  wire \$24 ;
  wire \$25 ;
  wire [18:0] \$26 ;
  wire [18:0] \$27 ;
  wire \$28 ;
  wire \$29 ;
  wire [18:0] \$3 ;
  wire [18:0] \$30 ;
  wire [18:0] \$31 ;
  wire \$32 ;
  wire \$33 ;
  wire [18:0] \$34 ;
  wire [18:0] \$35 ;
  wire \$36 ;
  wire \$37 ;
  wire [18:0] \$38 ;
  wire [18:0] \$39 ;
  wire \$4 ;
  wire \$40 ;
  wire \$41 ;
  wire [18:0] \$42 ;
  wire [18:0] \$43 ;
  wire \$44 ;
  wire \$45 ;
  wire [18:0] \$46 ;
  wire [18:0] \$47 ;
  wire \$48 ;
  wire \$49 ;
  wire \$5 ;
  wire [18:0] \$50 ;
  wire [18:0] \$51 ;
  wire \$52 ;
  wire \$53 ;
  wire [18:0] \$54 ;
  wire [18:0] \$55 ;
  wire \$56 ;
  wire \$57 ;
  wire [18:0] \$58 ;
  wire [18:0] \$59 ;
  wire [18:0] \$6 ;
  wire \$60 ;
  wire \$61 ;
  wire [18:0] \$62 ;
  wire [18:0] \$63 ;
  wire \$64 ;
  wire [18:0] \$7 ;
  wire \$8 ;
  wire \$9 ;
  (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:44" *)
  wire [31:0] \$signal ;
  (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:47" *)
  wire [17:0] \$signal$10 ;
  (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:46" *)
  wire [17:0] \$signal$11 ;
  (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:44" *)
  wire [31:0] \$signal$12 ;
  (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:48" *)
  reg [17:0] \$signal$13 ;
  (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:45" *)
  wire [15:0] \$signal$14 ;
  (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:47" *)
  wire [17:0] \$signal$15 ;
  (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:46" *)
  wire [17:0] \$signal$16 ;
  (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:44" *)
  wire [31:0] \$signal$17 ;
  (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:48" *)
  reg [17:0] \$signal$18 ;
  (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:45" *)
  wire [15:0] \$signal$19 ;
  (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:47" *)
  wire [17:0] \$signal$20 ;
  (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:46" *)
  wire [17:0] \$signal$21 ;
  (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:44" *)
  wire [31:0] \$signal$22 ;
  (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:48" *)
  reg [17:0] \$signal$23 ;
  (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:45" *)
  wire [15:0] \$signal$24 ;
  (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:47" *)
  wire [17:0] \$signal$25 ;
  (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:46" *)
  wire [17:0] \$signal$26 ;
  (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:44" *)
  wire [31:0] \$signal$27 ;
  (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:48" *)
  reg [17:0] \$signal$28 ;
  (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:45" *)
  wire [15:0] \$signal$29 ;
  (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:45" *)
  wire [15:0] \$signal$3 ;
  (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:47" *)
  wire [17:0] \$signal$30 ;
  (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:46" *)
  wire [17:0] \$signal$31 ;
  (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:44" *)
  wire [31:0] \$signal$32 ;
  (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:48" *)
  reg [17:0] \$signal$33 ;
  (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:45" *)
  wire [15:0] \$signal$34 ;
  (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:47" *)
  wire [17:0] \$signal$35 ;
  (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:46" *)
  wire [17:0] \$signal$36 ;
  (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:44" *)
  wire [31:0] \$signal$37 ;
  (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:48" *)
  reg [17:0] \$signal$38 ;
  (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:45" *)
  wire [15:0] \$signal$39 ;
  (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:48" *)
  wire [17:0] \$signal$4 ;
  (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:47" *)
  wire [17:0] \$signal$40 ;
  (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:46" *)
  wire [17:0] \$signal$41 ;
  (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:44" *)
  wire [31:0] \$signal$42 ;
  (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:48" *)
  reg [17:0] \$signal$43 ;
  (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:45" *)
  wire [15:0] \$signal$44 ;
  (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:47" *)
  wire [17:0] \$signal$45 ;
  (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:46" *)
  wire [17:0] \$signal$46 ;
  (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:44" *)
  wire [31:0] \$signal$47 ;
  (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:48" *)
  reg [17:0] \$signal$48 ;
  (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:45" *)
  wire [15:0] \$signal$49 ;
  (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:47" *)
  wire [17:0] \$signal$5 ;
  (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:47" *)
  wire [17:0] \$signal$50 ;
  (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:46" *)
  wire [17:0] \$signal$51 ;
  (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:44" *)
  wire [31:0] \$signal$52 ;
  (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:48" *)
  reg [17:0] \$signal$53 ;
  (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:45" *)
  wire [15:0] \$signal$54 ;
  (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:47" *)
  wire [17:0] \$signal$55 ;
  (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:46" *)
  wire [17:0] \$signal$56 ;
  (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:44" *)
  wire [31:0] \$signal$57 ;
  (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:48" *)
  reg [17:0] \$signal$58 ;
  (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:45" *)
  wire [15:0] \$signal$59 ;
  (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:46" *)
  wire [17:0] \$signal$6 ;
  (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:47" *)
  wire [17:0] \$signal$60 ;
  (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:46" *)
  wire [17:0] \$signal$61 ;
  (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:44" *)
  wire [31:0] \$signal$62 ;
  (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:48" *)
  reg [17:0] \$signal$63 ;
  (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:45" *)
  wire [15:0] \$signal$64 ;
  (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:47" *)
  wire [17:0] \$signal$65 ;
  (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:46" *)
  wire [17:0] \$signal$66 ;
  (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:44" *)
  wire [31:0] \$signal$67 ;
  (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:48" *)
  reg [17:0] \$signal$68 ;
  (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:45" *)
  wire [15:0] \$signal$69 ;
  (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:44" *)
  wire [31:0] \$signal$7 ;
  (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:47" *)
  wire [17:0] \$signal$70 ;
  (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:46" *)
  wire [17:0] \$signal$71 ;
  (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:44" *)
  wire [31:0] \$signal$72 ;
  (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:48" *)
  reg [17:0] \$signal$73 ;
  (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:45" *)
  wire [15:0] \$signal$74 ;
  (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:47" *)
  wire [17:0] \$signal$75 ;
  (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:46" *)
  wire [17:0] \$signal$76 ;
  (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:44" *)
  wire [31:0] \$signal$77 ;
  (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:48" *)
  reg [17:0] \$signal$78 ;
  (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:45" *)
  wire [15:0] \$signal$79 ;
  (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:48" *)
  reg [17:0] \$signal$8 ;
  (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:47" *)
  wire [17:0] \$signal$80 ;
  (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:46" *)
  wire [17:0] \$signal$81 ;
  (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:44" *)
  wire [31:0] \$signal$82 ;
  (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:48" *)
  reg [17:0] \$signal$83 ;
  (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:45" *)
  wire [15:0] \$signal$84 ;
  (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:45" *)
  wire [15:0] \$signal$9 ;
  (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:44" *)
  input [31:0] num;
  wire [31:0] num;
  (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:45" *)
  output [15:0] result;
  wire [15:0] result;
  assign \$36  = ~ (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:74" *) \$signal$48 [17];
  assign \$38  = { \$signal$48 [15:0], num[13:12] } + (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:70" *) { \$4 , \$8 , \$12 , \$16 , \$20 , \$24 , \$28 , \$32 , \$36 , \$signal$48 [17], 1'h1 };
  assign \$39  = { \$signal$48 [15:0], num[13:12] } - (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:72" *) { \$4 , \$8 , \$12 , \$16 , \$20 , \$24 , \$28 , \$32 , \$36 , \$signal$48 [17], 1'h1 };
  assign \$40  = ~ (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:74" *) \$signal$53 [17];
  assign \$42  = { \$signal$53 [15:0], num[11:10] } + (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:70" *) { \$4 , \$8 , \$12 , \$16 , \$20 , \$24 , \$28 , \$32 , \$36 , \$40 , \$signal$53 [17], 1'h1 };
  assign \$43  = { \$signal$53 [15:0], num[11:10] } - (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:72" *) { \$4 , \$8 , \$12 , \$16 , \$20 , \$24 , \$28 , \$32 , \$36 , \$40 , \$signal$53 [17], 1'h1 };
  assign \$44  = ~ (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:74" *) \$signal$58 [17];
  assign \$46  = { \$signal$58 [15:0], num[9:8] } + (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:70" *) { \$4 , \$8 , \$12 , \$16 , \$20 , \$24 , \$28 , \$32 , \$36 , \$40 , \$44 , \$signal$58 [17], 1'h1 };
  assign \$47  = { \$signal$58 [15:0], num[9:8] } - (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:72" *) { \$4 , \$8 , \$12 , \$16 , \$20 , \$24 , \$28 , \$32 , \$36 , \$40 , \$44 , \$signal$58 [17], 1'h1 };
  assign \$48  = ~ (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:74" *) \$signal$63 [17];
  assign \$50  = { \$signal$63 [15:0], num[7:6] } + (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:70" *) { \$4 , \$8 , \$12 , \$16 , \$20 , \$24 , \$28 , \$32 , \$36 , \$40 , \$44 , \$48 , \$signal$63 [17], 1'h1 };
  assign \$51  = { \$signal$63 [15:0], num[7:6] } - (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:72" *) { \$4 , \$8 , \$12 , \$16 , \$20 , \$24 , \$28 , \$32 , \$36 , \$40 , \$44 , \$48 , \$signal$63 [17], 1'h1 };
  assign \$52  = ~ (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:74" *) \$signal$68 [17];
  assign \$54  = { \$signal$68 [15:0], num[5:4] } + (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:70" *) { \$4 , \$8 , \$12 , \$16 , \$20 , \$24 , \$28 , \$32 , \$36 , \$40 , \$44 , \$48 , \$52 , \$signal$68 [17], 1'h1 };
  assign \$55  = { \$signal$68 [15:0], num[5:4] } - (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:72" *) { \$4 , \$8 , \$12 , \$16 , \$20 , \$24 , \$28 , \$32 , \$36 , \$40 , \$44 , \$48 , \$52 , \$signal$68 [17], 1'h1 };
  assign \$56  = ~ (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:74" *) \$signal$73 [17];
  assign \$58  = { \$signal$73 [15:0], num[3:2] } + (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:70" *) { \$4 , \$8 , \$12 , \$16 , \$20 , \$24 , \$28 , \$32 , \$36 , \$40 , \$44 , \$48 , \$52 , \$56 , \$signal$73 [17], 1'h1 };
  assign \$59  = { \$signal$73 [15:0], num[3:2] } - (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:72" *) { \$4 , \$8 , \$12 , \$16 , \$20 , \$24 , \$28 , \$32 , \$36 , \$40 , \$44 , \$48 , \$52 , \$56 , \$signal$73 [17], 1'h1 };
  assign \$60  = ~ (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:74" *) \$signal$78 [17];
  assign \$62  = { \$signal$78 [15:0], num[1:0] } + (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:70" *) { \$4 , \$8 , \$12 , \$16 , \$20 , \$24 , \$28 , \$32 , \$36 , \$40 , \$44 , \$48 , \$52 , \$56 , \$60 , \$signal$78 [17], 1'h1 };
  assign \$63  = { \$signal$78 [15:0], num[1:0] } - (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:72" *) { \$4 , \$8 , \$12 , \$16 , \$20 , \$24 , \$28 , \$32 , \$36 , \$40 , \$44 , \$48 , \$52 , \$56 , \$60 , \$signal$78 [17], 1'h1 };
  assign \$64  = ~ (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:74" *) \$signal$83 [17];
  assign \$2  = num[31:30] + (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:70" *) 1'h1;
  assign \$3  = num[31:30] - (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:72" *) 1'h1;
  assign \$4  = ~ (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:74" *) \$signal$8 [17];
  assign \$6  = { \$signal$8 [15:0], num[29:28] } + (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:70" *) { \$4 , \$signal$8 [17], 1'h1 };
  assign \$7  = { \$signal$8 [15:0], num[29:28] } - (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:72" *) { \$4 , \$signal$8 [17], 1'h1 };
  assign \$8  = ~ (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:74" *) \$signal$13 [17];
  assign \$10  = { \$signal$13 [15:0], num[27:26] } + (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:70" *) { \$4 , \$8 , \$signal$13 [17], 1'h1 };
  assign \$11  = { \$signal$13 [15:0], num[27:26] } - (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:72" *) { \$4 , \$8 , \$signal$13 [17], 1'h1 };
  assign \$12  = ~ (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:74" *) \$signal$18 [17];
  assign \$14  = { \$signal$18 [15:0], num[25:24] } + (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:70" *) { \$4 , \$8 , \$12 , \$signal$18 [17], 1'h1 };
  assign \$15  = { \$signal$18 [15:0], num[25:24] } - (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:72" *) { \$4 , \$8 , \$12 , \$signal$18 [17], 1'h1 };
  assign \$16  = ~ (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:74" *) \$signal$23 [17];
  assign \$18  = { \$signal$23 [15:0], num[23:22] } + (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:70" *) { \$4 , \$8 , \$12 , \$16 , \$signal$23 [17], 1'h1 };
  assign \$19  = { \$signal$23 [15:0], num[23:22] } - (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:72" *) { \$4 , \$8 , \$12 , \$16 , \$signal$23 [17], 1'h1 };
  assign \$20  = ~ (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:74" *) \$signal$28 [17];
  assign \$22  = { \$signal$28 [15:0], num[21:20] } + (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:70" *) { \$4 , \$8 , \$12 , \$16 , \$20 , \$signal$28 [17], 1'h1 };
  assign \$23  = { \$signal$28 [15:0], num[21:20] } - (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:72" *) { \$4 , \$8 , \$12 , \$16 , \$20 , \$signal$28 [17], 1'h1 };
  assign \$24  = ~ (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:74" *) \$signal$33 [17];
  assign \$26  = { \$signal$33 [15:0], num[19:18] } + (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:70" *) { \$4 , \$8 , \$12 , \$16 , \$20 , \$24 , \$signal$33 [17], 1'h1 };
  assign \$27  = { \$signal$33 [15:0], num[19:18] } - (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:72" *) { \$4 , \$8 , \$12 , \$16 , \$20 , \$24 , \$signal$33 [17], 1'h1 };
  assign \$28  = ~ (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:74" *) \$signal$38 [17];
  assign \$30  = { \$signal$38 [15:0], num[17:16] } + (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:70" *) { \$4 , \$8 , \$12 , \$16 , \$20 , \$24 , \$28 , \$signal$38 [17], 1'h1 };
  assign \$31  = { \$signal$38 [15:0], num[17:16] } - (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:72" *) { \$4 , \$8 , \$12 , \$16 , \$20 , \$24 , \$28 , \$signal$38 [17], 1'h1 };
  assign \$32  = ~ (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:74" *) \$signal$43 [17];
  assign \$34  = { \$signal$43 [15:0], num[15:14] } + (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:70" *) { \$4 , \$8 , \$12 , \$16 , \$20 , \$24 , \$28 , \$32 , \$signal$43 [17], 1'h1 };
  assign \$35  = { \$signal$43 [15:0], num[15:14] } - (* src = "/home/user/SDR-HLS/5.NewModules/SquareRoot/combinatorial/amaranth/sqrt_combinatorial.py:72" *) { \$4 , \$8 , \$12 , \$16 , \$20 , \$24 , \$28 , \$32 , \$signal$43 [17], 1'h1 };
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    if (\$1 ) begin
      \$signal$8  = \$2 [17:0];
    end else begin
      \$signal$8  = \$3 [17:0];
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    if (\$5 ) begin
      \$signal$13  = \$6 [17:0];
    end else begin
      \$signal$13  = \$7 [17:0];
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    if (\$9 ) begin
      \$signal$18  = \$10 [17:0];
    end else begin
      \$signal$18  = \$11 [17:0];
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    if (\$13 ) begin
      \$signal$23  = \$14 [17:0];
    end else begin
      \$signal$23  = \$15 [17:0];
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    if (\$17 ) begin
      \$signal$28  = \$18 [17:0];
    end else begin
      \$signal$28  = \$19 [17:0];
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    if (\$21 ) begin
      \$signal$33  = \$22 [17:0];
    end else begin
      \$signal$33  = \$23 [17:0];
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    if (\$25 ) begin
      \$signal$38  = \$26 [17:0];
    end else begin
      \$signal$38  = \$27 [17:0];
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    if (\$29 ) begin
      \$signal$43  = \$30 [17:0];
    end else begin
      \$signal$43  = \$31 [17:0];
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    if (\$33 ) begin
      \$signal$48  = \$34 [17:0];
    end else begin
      \$signal$48  = \$35 [17:0];
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    if (\$37 ) begin
      \$signal$53  = \$38 [17:0];
    end else begin
      \$signal$53  = \$39 [17:0];
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    if (\$41 ) begin
      \$signal$58  = \$42 [17:0];
    end else begin
      \$signal$58  = \$43 [17:0];
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    if (\$45 ) begin
      \$signal$63  = \$46 [17:0];
    end else begin
      \$signal$63  = \$47 [17:0];
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    if (\$49 ) begin
      \$signal$68  = \$50 [17:0];
    end else begin
      \$signal$68  = \$51 [17:0];
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    if (\$53 ) begin
      \$signal$73  = \$54 [17:0];
    end else begin
      \$signal$73  = \$55 [17:0];
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    if (\$57 ) begin
      \$signal$78  = \$58 [17:0];
    end else begin
      \$signal$78  = \$59 [17:0];
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2352:dump_module$1 ) begin end
    (* full_case = 32'd1 *)
    if (\$61 ) begin
      \$signal$83  = \$62 [17:0];
    end else begin
      \$signal$83  = \$63 [17:0];
    end
  end
  assign \$signal  = num;
  assign \$signal$3  = 16'h0000;
  assign \$signal$4  = 18'h00000;
  assign \$signal$5  = 18'h00001;
  assign \$signal$6  = { 16'h0000, num[31:30] };
  assign \$signal$7  = { num[29:0], 2'h0 };
  assign \$signal$9  = { 15'h0000, \$4  };
  assign \$signal$10  = { 15'h0000, \$4 , \$signal$8 [17], 1'h1 };
  assign \$signal$11  = { \$signal$8 [15:0], num[29:28] };
  assign \$signal$12  = { num[27:0], 4'h0 };
  assign \$signal$14  = { 14'h0000, \$4 , \$8  };
  assign \$signal$15  = { 14'h0000, \$4 , \$8 , \$signal$13 [17], 1'h1 };
  assign \$signal$16  = { \$signal$13 [15:0], num[27:26] };
  assign \$signal$17  = { num[25:0], 6'h00 };
  assign \$signal$19  = { 13'h0000, \$4 , \$8 , \$12  };
  assign \$signal$20  = { 13'h0000, \$4 , \$8 , \$12 , \$signal$18 [17], 1'h1 };
  assign \$signal$21  = { \$signal$18 [15:0], num[25:24] };
  assign \$signal$22  = { num[23:0], 8'h00 };
  assign \$signal$24  = { 12'h000, \$4 , \$8 , \$12 , \$16  };
  assign \$signal$25  = { 12'h000, \$4 , \$8 , \$12 , \$16 , \$signal$23 [17], 1'h1 };
  assign \$signal$26  = { \$signal$23 [15:0], num[23:22] };
  assign \$signal$27  = { num[21:0], 10'h000 };
  assign \$signal$29  = { 11'h000, \$4 , \$8 , \$12 , \$16 , \$20  };
  assign \$signal$30  = { 11'h000, \$4 , \$8 , \$12 , \$16 , \$20 , \$signal$28 [17], 1'h1 };
  assign \$signal$31  = { \$signal$28 [15:0], num[21:20] };
  assign \$signal$32  = { num[19:0], 12'h000 };
  assign \$signal$34  = { 10'h000, \$4 , \$8 , \$12 , \$16 , \$20 , \$24  };
  assign \$signal$35  = { 10'h000, \$4 , \$8 , \$12 , \$16 , \$20 , \$24 , \$signal$33 [17], 1'h1 };
  assign \$signal$36  = { \$signal$33 [15:0], num[19:18] };
  assign \$signal$37  = { num[17:0], 14'h0000 };
  assign \$signal$39  = { 9'h000, \$4 , \$8 , \$12 , \$16 , \$20 , \$24 , \$28  };
  assign \$signal$40  = { 9'h000, \$4 , \$8 , \$12 , \$16 , \$20 , \$24 , \$28 , \$signal$38 [17], 1'h1 };
  assign \$signal$41  = { \$signal$38 [15:0], num[17:16] };
  assign \$signal$42  = { num[15:0], 16'h0000 };
  assign \$signal$44  = { 8'h00, \$4 , \$8 , \$12 , \$16 , \$20 , \$24 , \$28 , \$32  };
  assign \$signal$45  = { 8'h00, \$4 , \$8 , \$12 , \$16 , \$20 , \$24 , \$28 , \$32 , \$signal$43 [17], 1'h1 };
  assign \$signal$46  = { \$signal$43 [15:0], num[15:14] };
  assign \$signal$47  = { num[13:0], 18'h00000 };
  assign \$signal$49  = { 7'h00, \$4 , \$8 , \$12 , \$16 , \$20 , \$24 , \$28 , \$32 , \$36  };
  assign \$signal$50  = { 7'h00, \$4 , \$8 , \$12 , \$16 , \$20 , \$24 , \$28 , \$32 , \$36 , \$signal$48 [17], 1'h1 };
  assign \$signal$51  = { \$signal$48 [15:0], num[13:12] };
  assign \$signal$52  = { num[11:0], 20'h00000 };
  assign \$signal$54  = { 6'h00, \$4 , \$8 , \$12 , \$16 , \$20 , \$24 , \$28 , \$32 , \$36 , \$40  };
  assign \$signal$55  = { 6'h00, \$4 , \$8 , \$12 , \$16 , \$20 , \$24 , \$28 , \$32 , \$36 , \$40 , \$signal$53 [17], 1'h1 };
  assign \$signal$56  = { \$signal$53 [15:0], num[11:10] };
  assign \$signal$57  = { num[9:0], 22'h000000 };
  assign \$signal$59  = { 5'h00, \$4 , \$8 , \$12 , \$16 , \$20 , \$24 , \$28 , \$32 , \$36 , \$40 , \$44  };
  assign \$signal$60  = { 5'h00, \$4 , \$8 , \$12 , \$16 , \$20 , \$24 , \$28 , \$32 , \$36 , \$40 , \$44 , \$signal$58 [17], 1'h1 };
  assign \$signal$61  = { \$signal$58 [15:0], num[9:8] };
  assign \$signal$62  = { num[7:0], 24'h000000 };
  assign \$signal$64  = { 4'h0, \$4 , \$8 , \$12 , \$16 , \$20 , \$24 , \$28 , \$32 , \$36 , \$40 , \$44 , \$48  };
  assign \$signal$65  = { 4'h0, \$4 , \$8 , \$12 , \$16 , \$20 , \$24 , \$28 , \$32 , \$36 , \$40 , \$44 , \$48 , \$signal$63 [17], 1'h1 };
  assign \$signal$66  = { \$signal$63 [15:0], num[7:6] };
  assign \$signal$67  = { num[5:0], 26'h0000000 };
  assign \$signal$69  = { 3'h0, \$4 , \$8 , \$12 , \$16 , \$20 , \$24 , \$28 , \$32 , \$36 , \$40 , \$44 , \$48 , \$52  };
  assign \$signal$70  = { 3'h0, \$4 , \$8 , \$12 , \$16 , \$20 , \$24 , \$28 , \$32 , \$36 , \$40 , \$44 , \$48 , \$52 , \$signal$68 [17], 1'h1 };
  assign \$signal$71  = { \$signal$68 [15:0], num[5:4] };
  assign \$signal$72  = { num[3:0], 28'h0000000 };
  assign \$signal$74  = { 2'h0, \$4 , \$8 , \$12 , \$16 , \$20 , \$24 , \$28 , \$32 , \$36 , \$40 , \$44 , \$48 , \$52 , \$56  };
  assign \$signal$75  = { 2'h0, \$4 , \$8 , \$12 , \$16 , \$20 , \$24 , \$28 , \$32 , \$36 , \$40 , \$44 , \$48 , \$52 , \$56 , \$signal$73 [17], 1'h1 };
  assign \$signal$76  = { \$signal$73 [15:0], num[3:2] };
  assign \$signal$77  = { num[1:0], 30'h00000000 };
  assign \$signal$79  = { 1'h0, \$4 , \$8 , \$12 , \$16 , \$20 , \$24 , \$28 , \$32 , \$36 , \$40 , \$44 , \$48 , \$52 , \$56 , \$60  };
  assign \$signal$80  = { 1'h0, \$4 , \$8 , \$12 , \$16 , \$20 , \$24 , \$28 , \$32 , \$36 , \$40 , \$44 , \$48 , \$52 , \$56 , \$60 , \$signal$78 [17], 1'h1 };
  assign \$signal$81  = { \$signal$78 [15:0], num[1:0] };
  assign \$signal$82  = 32'd0;
  assign \$signal$84  = { \$4 , \$8 , \$12 , \$16 , \$20 , \$24 , \$28 , \$32 , \$36 , \$40 , \$44 , \$48 , \$52 , \$56 , \$60 , \$64  };
  assign result = { \$4 , \$8 , \$12 , \$16 , \$20 , \$24 , \$28 , \$32 , \$36 , \$40 , \$44 , \$48 , \$52 , \$56 , \$60 , \$64  };
  assign \$1  = 1'h0;
  assign \$5  = \$signal$8 [17];
  assign \$9  = \$signal$13 [17];
  assign \$13  = \$signal$18 [17];
  assign \$17  = \$signal$23 [17];
  assign \$21  = \$signal$28 [17];
  assign \$25  = \$signal$33 [17];
  assign \$29  = \$signal$38 [17];
  assign \$33  = \$signal$43 [17];
  assign \$37  = \$signal$48 [17];
  assign \$41  = \$signal$53 [17];
  assign \$45  = \$signal$58 [17];
  assign \$49  = \$signal$63 [17];
  assign \$53  = \$signal$68 [17];
  assign \$57  = \$signal$73 [17];
  assign \$61  = \$signal$78 [17];
endmodule
