/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.13.0.56.2 */
/* Module Version: 3.5 */
/* Wed Feb 28 16:18:37 2024 */

/* parameterized module instance */
NCOAdder __ (.DataA( ), .DataB( ), .Clock( ), .Reset( ), .Result( ));
